// Coffee variety flavor data
// vendorNotes: WCR Variety Catalog, SCA cupping notes, specialty roaster tasting sheets
// userNotes: r/Coffee, r/espresso, Home-Barista.com, PerfectDailyGrind user comments,
//   CoffeeReview.com taster notes, specialty forum discussions (2020–2025)

export type FlavorCategory = "floral" | "fruity" | "sweet" | "chocolate" | "balanced" | "bold";

export type FlavorScores = {
  acidity: number;    // 1–10
  body: number;       // 1–10
  sweetness: number;  // 1–10
  floral: number;     // 1–10
  fruity: number;     // 1–10
  chocolate: number;  // 1–10
};

export type Variety = {
  id: string;
  name: string;       // Chinese name
  nameEn: string;     // English name
  category: FlavorCategory;
  origins: string[];
  lineage: string;
  vendor: FlavorScores;
  user: FlavorScores;
  vendorNotes: string[];
  userNotes: string[];
};

export const VARIETIES: Variety[] = [
  {
    id: "typica",
    name: "鐵比卡",
    nameEn: "Typica",
    category: "balanced",
    origins: ["衣索比亞", "葉門", "中南美洲", "亞洲"],
    lineage: "阿拉比卡原生品種之一，遍布全球的祖先品種",
    vendor: { acidity: 5.5, body: 5.0, sweetness: 6.0, floral: 4.5, fruity: 4.5, chocolate: 5.5 },
    user:   { acidity: 5.2, body: 5.2, sweetness: 5.5, floral: 3.8, fruity: 4.0, chocolate: 5.8 },
    vendorNotes: ["奶油感", "溫和花香", "楓糖", "檸檬皮"],
    userNotes:   ["乾淨順口但不驚豔", "中性不突出，很多人第一杯就是鐵比卡", "論壇常有人說「這就是咖啡的本來面目」", "尾韻帶甜，很適合日曬"],
  },
  {
    id: "bourbon",
    name: "波旁",
    nameEn: "Bourbon",
    category: "balanced",
    origins: ["留尼旺島", "中南美洲", "東非"],
    lineage: "鐵比卡突變種，由法國傳教士引入留尼旺島",
    vendor: { acidity: 6.5, body: 6.5, sweetness: 7.5, floral: 5.0, fruity: 6.5, chocolate: 5.0 },
    user:   { acidity: 6.2, body: 6.0, sweetness: 6.8, floral: 4.2, fruity: 5.8, chocolate: 5.5 },
    vendorNotes: ["紅莓", "太妃糖", "牛奶巧克力", "柑橘"],
    userNotes:   ["甜感是真的強，不是想像", "紅波旁：莓果巧克力感；黃波旁：蜂蜜杏桃更甜潤", "粉波旁曾有人形容「像茉莉配荔枝」", "論壇最常推的入門品種之一，不容易踩雷"],
  },
  {
    id: "gesha",
    name: "藝妓",
    nameEn: "Gesha / Geisha",
    category: "floral",
    origins: ["衣索比亞（Gesha 村）", "巴拿馬", "哥倫比亞"],
    lineage: "衣索比亞原生品種，1950年代引入巴拿馬後聲名大噪",
    vendor: { acidity: 8.5, body: 4.5, sweetness: 8.0, floral: 9.5, fruity: 9.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 4.2, sweetness: 7.2, floral: 9.0, fruity: 8.5, chocolate: 1.2 },
    vendorNotes: ["茉莉花", "佛手柑", "熱帶水果", "百香果", "玫瑰"],
    userNotes:   ["喝到好批次：覆盆子杏桃帶佛手柑，軟甜如茶（CoffeeReview用戶描述）", "冷卻後酸感才出來，像在喝花茶", "有人覺得CP值不符，但 Esmeralda 批次幾乎無可挑剔", "論壇兩極：有人說改變了對咖啡的認知，有人說不值那個價"],
  },
  {
    id: "sl28",
    name: "SL28",
    nameEn: "SL28",
    category: "bold",
    origins: ["肯亞"],
    lineage: "Scott Labs 1930年代篩選，可能源自 Tanganyika drought-resistant 品種",
    vendor: { acidity: 9.0, body: 7.5, sweetness: 7.0, floral: 5.5, fruity: 8.5, chocolate: 3.5 },
    user:   { acidity: 8.5, body: 7.0, sweetness: 6.2, floral: 5.0, fruity: 8.0, chocolate: 4.0 },
    vendorNotes: ["黑醋栗", "柚子", "番茄", "複雜酸質"],
    userNotes:   ["水洗批次黑醋栗柚子，酸感如電（Home-Barista 常見描述）", "有人說喝完嘴巴還能感覺磷酸感，好幾分鐘不散", "不適合習慣淡味的人，但重口味愛好者奉為圭臬", "好的批次有「夏日番茄＋黑醋栗」的甜酸交疊感"],
  },
  {
    id: "sl34",
    name: "SL34",
    nameEn: "SL34",
    category: "bold",
    origins: ["肯亞"],
    lineage: "Scott Labs 篩選，源自法國傳教士 Bourbon 品系",
    vendor: { acidity: 8.5, body: 9.0, sweetness: 7.0, floral: 4.5, fruity: 7.0, chocolate: 5.5 },
    user:   { acidity: 8.0, body: 8.5, sweetness: 6.5, floral: 4.0, fruity: 6.5, chocolate: 6.0 },
    vendorNotes: ["黑莓", "厚重醇感", "深色水果", "磷酸質感"],
    userNotes:   ["酸強但body完全撐得住，不會失衡", "比SL28更厚實圓融，少了一些尖銳", "Wine-like的深色水果感，像葡萄酒迷說的那種「漿果尾韻」", "常和SL28一起出現在肯亞頂批，兩支一起喝才能比較"],
  },
  {
    id: "caturra",
    name: "卡杜拉",
    nameEn: "Caturra",
    category: "fruity",
    origins: ["巴西", "哥倫比亞", "中美洲"],
    lineage: "波旁自然突變種（矮化），1937年巴西發現",
    vendor: { acidity: 7.5, body: 4.0, sweetness: 5.0, floral: 3.5, fruity: 6.5, chocolate: 4.5 },
    user:   { acidity: 7.2, body: 3.8, sweetness: 4.5, floral: 3.0, fruity: 6.0, chocolate: 4.2 },
    vendorNotes: ["柑橘", "黃色水果", "清爽酸質", "輕盈"],
    userNotes:   ["柑橘酸感清亮但有時偏尖鋭，不夠圓潤", "body薄是真的，有人說「喝起來水水的」", "水洗卡杜拉清爽；日曬則意外多了果香層次", "性價比高，哥倫比亞精品莊園很常見"],
  },
  {
    id: "catuai",
    name: "卡杜艾",
    nameEn: "Catuai",
    category: "balanced",
    origins: ["巴西", "中美洲"],
    lineage: "新世界 × 卡杜拉 雜交，IAPAR 1949年培育",
    vendor: { acidity: 6.0, body: 6.0, sweetness: 6.5, floral: 3.5, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 5.8, body: 5.8, sweetness: 6.0, floral: 3.0, fruity: 5.0, chocolate: 6.0 },
    vendorNotes: ["焦糖", "堅果", "輕微果酸", "均衡"],
    userNotes:   ["高海拔批次才有真正的明亮酸質，低海拔則平淡無奇", "黃卡杜艾比紅的更甜更花香，兩者論壇評分差很多", "巴西卡杜艾是義式配方豆的主力，用戶評語多在「穩定可靠」", "「不驚豔但不出錯」是最常聽到的描述"],
  },
  {
    id: "mundo-novo",
    name: "新世界",
    nameEn: "Mundo Novo",
    category: "chocolate",
    origins: ["巴西"],
    lineage: "波旁 × 蘇門答臘鐵比卡 自然雜交，1943年巴西發現",
    vendor: { acidity: 5.0, body: 8.5, sweetness: 6.0, floral: 2.5, fruity: 4.0, chocolate: 7.5 },
    user:   { acidity: 4.8, body: 8.0, sweetness: 5.5, floral: 2.0, fruity: 3.5, chocolate: 8.0 },
    vendorNotes: ["黑巧克力", "核桃", "厚重醇感", "低調果酸"],
    userNotes:   ["body厚實是真的，專業烘豆師推義式首選之一", "巧克力堅果感很突出，配甜點或蛋糕被形容為「天作之合」", "低酸特性讓很多人覺得「很舒服喝不累」", "深焙後核桃焦糖感加強，淺焙則平淡；不適合追求花果香的人"],
  },
  {
    id: "maragogipe",
    name: "象豆",
    nameEn: "Maragogipe",
    category: "sweet",
    origins: ["巴西", "瓜地馬拉", "墨西哥"],
    lineage: "鐵比卡突變種（超大豆），1870年巴西 Maragogipe 地區發現",
    vendor: { acidity: 4.0, body: 3.5, sweetness: 6.5, floral: 4.5, fruity: 4.0, chocolate: 4.0 },
    user:   { acidity: 3.8, body: 3.5, sweetness: 6.0, floral: 4.0, fruity: 3.5, chocolate: 4.0 },
    vendorNotes: ["細緻甜感", "木質香", "淡花香", "清淡優雅"],
    userNotes:   ["豆子超大粒、孔隙多，這是大家最常討論的第一印象", "口味評價非常分化：好的批次甜潤優雅，差的批次水薄無味", "被形容為「notoriously inconsistent」，批次選擇決定一切", "有人做法壓壺效果很好，有人試了各種方法還是喝不出特色"],
  },
  {
    id: "pacamara",
    name: "帕卡瑪拉",
    nameEn: "Pacamara",
    category: "floral",
    origins: ["薩爾瓦多", "瓜地馬拉", "宏都拉斯"],
    lineage: "帕卡斯 × 象豆 人工雜交，1958年薩爾瓦多 ISIC 培育",
    vendor: { acidity: 7.0, body: 6.5, sweetness: 7.5, floral: 7.5, fruity: 7.5, chocolate: 2.5 },
    user:   { acidity: 6.8, body: 6.0, sweetness: 7.0, floral: 7.0, fruity: 7.0, chocolate: 2.8 },
    vendorNotes: ["茉莉花", "芒果", "熱帶水果", "厚實花香"],
    userNotes:   ["好批次：「令人驚嘆地滑順甜潤，芒果茉莉交疊」（CoffeeReview 用戶）", "差批次：帶蔬菜、蘑菇甚至紙板味，而且差批次「非常普遍」", "有人做法壓壺讚不絕口，有人試各種沖法還是完全沒甜感", "Cup of Excellence 常客，但優劣落差是所有品種裡最大的之一"],
  },
  {
    id: "pacas",
    name: "帕卡斯",
    nameEn: "Pacas",
    category: "sweet",
    origins: ["薩爾瓦多", "宏都拉斯"],
    lineage: "波旁自然突變種（矮化），1949年薩爾瓦多 Pacas 家族農場發現",
    vendor: { acidity: 6.0, body: 5.5, sweetness: 7.0, floral: 4.5, fruity: 5.5, chocolate: 5.0 },
    user:   { acidity: 5.8, body: 5.2, sweetness: 6.5, floral: 4.0, fruity: 5.0, chocolate: 5.2 },
    vendorNotes: ["蜂蜜甜感", "牛奶巧克力", "杏桃", "柑橘皮"],
    userNotes:   ["甜而不膩", "像波旁的精緻版", "很好入門", "蜜處理更甜"],
  },
  {
    id: "mocha",
    name: "摩卡（品種）",
    nameEn: "Yemen Mocha",
    category: "chocolate",
    origins: ["葉門", "衣索比亞"],
    lineage: "葉門原生古老品種，與現代義式「摩卡咖啡」同名但不同",
    vendor: { acidity: 6.5, body: 5.0, sweetness: 6.0, floral: 5.5, fruity: 5.0, chocolate: 7.0 },
    user:   { acidity: 6.2, body: 4.8, sweetness: 5.5, floral: 5.0, fruity: 4.5, chocolate: 7.2 },
    vendorNotes: ["黑巧克力", "肉桂", "野生莓果", "土壤感"],
    userNotes:   ["很野性的風味", "有點藍調感", "巧克力香氣", "葉門批次味道很特別"],
  },
  {
    id: "ethiopian-heirloom",
    name: "衣索比亞原生種",
    nameEn: "Ethiopian Heirloom",
    category: "floral",
    origins: ["衣索比亞（耶加雪菲、西達摩、哈拉爾）"],
    lineage: "衣索比亞地方原生品種總稱，基因多樣性最高",
    vendor: { acidity: 8.0, body: 4.0, sweetness: 8.0, floral: 8.5, fruity: 8.5, chocolate: 1.5 },
    user:   { acidity: 7.5, body: 4.0, sweetness: 7.2, floral: 8.0, fruity: 8.0, chocolate: 1.8 },
    vendorNotes: ["茉莉花", "藍莓", "桃子", "熱帶水果", "玫瑰"],
    userNotes:   ["水洗耶加雪菲：論壇公認「茉莉花香最乾淨的表達之一」", "日曬哈拉爾：「像在喝果汁，藍莓野莓發酵感很重」", "Sidama / Guji 批次近年評價更高，被說有更多結構感", "每批地區差異極大，買同個產區不同莊園風味可能天差地別"],
  },
  {
    id: "sudan-rume",
    name: "蘇丹盧美",
    nameEn: "Sudan Rume",
    category: "fruity",
    origins: ["蘇丹（Boma Plateau）", "衣索比亞"],
    lineage: "阿拉比卡原始族群之一，1940年代從蘇丹引入",
    vendor: { acidity: 8.5, body: 4.5, sweetness: 7.5, floral: 7.0, fruity: 8.0, chocolate: 2.0 },
    user:   { acidity: 8.0, body: 4.5, sweetness: 7.0, floral: 6.5, fruity: 7.5, chocolate: 2.5 },
    vendorNotes: ["佛手柑", "百香果", "杏桃", "清亮酸質"],
    userNotes:   ["「芒果鳳梨熱帶果香衝出來，酸感精準不刺」（CoffeeReview 品鑑描述）", "有用戶描述喝到的是「紫羅蘭薰衣草帶肉桂」，另一批次又是「茉莉尤加利橙皮」——批次差異驚人", "極度稀有，能找到的批次本身就不多，Home-Barista 論壇常有人問去哪買", "「比藝妓更原始、更野性的花香，但沒那麼精緻」是多數喝過的人的共識"],
  },
  {
    id: "wush-wush",
    name: "諸奇",
    nameEn: "Wush Wush",
    category: "floral",
    origins: ["衣索比亞（卡法地區）"],
    lineage: "衣索比亞卡法森林原生種，近年在哥倫比亞等地廣泛種植",
    vendor: { acidity: 8.5, body: 3.8, sweetness: 7.5, floral: 9.0, fruity: 8.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 3.8, sweetness: 7.0, floral: 8.5, fruity: 7.5, chocolate: 1.8 },
    vendorNotes: ["茉莉花", "薰衣草", "荔枝", "玫瑰水"],
    userNotes:   ["「Unlike anything I had ever tasted before」是論壇最常被引用的第一反應", "有人說「極度茶感、像草莓荔枝花水」，有人說「像葡萄酒，飽滿而複雜」——同一品種", "日曬版近乎甜點感，幾乎感覺不到酸；水洗版更透明花香", "比藝妓稀少，但識貨的人說它不遜色甚至更野性"],
  },
  {
    id: "villa-sarchi",
    name: "薇拉薩奇",
    nameEn: "Villa Sarchi",
    category: "fruity",
    origins: ["哥斯大黎加"],
    lineage: "波旁自然矮化突變種，1960年代哥斯大黎加 Villa Sarchi 地區發現",
    vendor: { acidity: 7.8, body: 4.5, sweetness: 6.0, floral: 5.0, fruity: 7.0, chocolate: 3.5 },
    user:   { acidity: 7.5, body: 4.3, sweetness: 5.5, floral: 4.5, fruity: 6.5, chocolate: 4.0 },
    vendorNotes: ["蘋果酸", "熱帶水果", "蜂蜜", "輕盈花香"],
    userNotes:   ["哥斯大黎加的代表之一", "酸感乾淨", "薄body但不澀", "蜜處理超好喝"],
  },
  {
    id: "laurina",
    name: "月光/羅利那",
    nameEn: "Laurina (Bourbon Pointu)",
    category: "sweet",
    origins: ["留尼旺島", "中美洲"],
    lineage: "波旁自然突變種，咖啡因含量為一般品種的一半",
    vendor: { acidity: 6.0, body: 4.0, sweetness: 8.0, floral: 6.5, fruity: 5.5, chocolate: 3.0 },
    user:   { acidity: 5.8, body: 4.0, sweetness: 7.5, floral: 6.0, fruity: 5.0, chocolate: 3.2 },
    vendorNotes: ["茉莉花茶", "白桃", "輕盈甜感", "極低苦澀"],
    userNotes:   ["2018年世界手沖賽冠軍用這支拿下冠軍，論壇因此開始注意到它", "「咖啡因只有一半，但味道一點不輸」是最多愛好者說的話", "甜感偏柑橘白桃，有人說「喝起來很純淨，不像一般咖啡那麼霸道」", "Home-Barista 論壇有完整討論串，有人說這是敏感族最理想的品種"],
  },
  {
    id: "java",
    name: "爪哇",
    nameEn: "Java (Abyssinia)",
    category: "chocolate",
    origins: ["印尼爪哇島", "東非"],
    lineage: "衣索比亞引入印尼的鐵比卡系品種，後來選育穩定",
    vendor: { acidity: 5.5, body: 6.5, sweetness: 5.5, floral: 3.5, fruity: 4.5, chocolate: 6.5 },
    user:   { acidity: 5.2, body: 6.2, sweetness: 5.0, floral: 3.0, fruity: 4.0, chocolate: 7.0 },
    vendorNotes: ["黑巧克力", "菸草", "香料", "木質感"],
    userNotes:   ["古典風味", "很傳統的咖啡感", "適合義式", "厚實有料"],
  },
  {
    id: "castillo",
    name: "卡斯提優",
    nameEn: "Castillo",
    category: "balanced",
    origins: ["哥倫比亞"],
    lineage: "哥倫比亞品種 × 帝汶混血 雜交，CENICAFÉ 2005年培育，抗銹病",
    vendor: { acidity: 6.5, body: 6.0, sweetness: 6.5, floral: 4.0, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 6.0, body: 5.8, sweetness: 5.8, floral: 3.5, fruity: 5.0, chocolate: 5.8 },
    vendorNotes: ["焦糖", "紅蘋果", "杏仁", "均衡酸甜"],
    userNotes:   ["比想像中好喝", "哥倫比亞主力品種", "不花俏但穩定", "水洗尤其乾淨"],
  },
  {
    id: "kent",
    name: "肯特",
    nameEn: "Kent",
    category: "chocolate",
    origins: ["印度"],
    lineage: "鐵比卡系選育，1920年代印度 Kent 先生的農場選育出",
    vendor: { acidity: 5.5, body: 6.0, sweetness: 5.5, floral: 3.0, fruity: 4.0, chocolate: 6.5 },
    user:   { acidity: 5.2, body: 5.8, sweetness: 5.0, floral: 2.8, fruity: 3.5, chocolate: 7.0 },
    vendorNotes: ["牛奶巧克力", "核桃", "印度香料", "低調酸質"],
    userNotes:   ["印度咖啡常見", "厚實傳統", "不複雜但紮實", "適合加牛奶"],
  },
  {
    id: "icatu",
    name: "伊卡圖",
    nameEn: "Icatu",
    category: "balanced",
    origins: ["巴西"],
    lineage: "羅布斯塔 × 波旁 再 × 卡杜艾，1985年巴西培育，抗銹病",
    vendor: { acidity: 5.8, body: 7.0, sweetness: 6.0, floral: 3.0, fruity: 5.0, chocolate: 6.5 },
    user:   { acidity: 5.5, body: 6.8, sweetness: 5.5, floral: 2.5, fruity: 4.5, chocolate: 7.0 },
    vendorNotes: ["黑糖", "核桃", "焦糖", "厚實body"],
    userNotes:   ["義式豆常見", "巧克力感佳", "body很強", "帶點羅豆感但不討厭"],
  },
  {
    id: "s795",
    name: "S795",
    nameEn: "S795",
    category: "balanced",
    origins: ["印度", "印尼"],
    lineage: "Kent × S288 (帝汶/阿拉比卡混血)，1940年代印度選育，耐銹病",
    vendor: { acidity: 5.8, body: 6.5, sweetness: 6.0, floral: 4.0, fruity: 4.5, chocolate: 6.0 },
    user:   { acidity: 5.5, body: 6.0, sweetness: 5.5, floral: 3.5, fruity: 4.0, chocolate: 6.5 },
    vendorNotes: ["牛奶巧克力", "蜂蜜甜", "香料感", "中等酸度"],
    userNotes:   ["曼特寧常用", "body紮實", "比純鐵比卡耐熱", "均衡好操作"],
  },
  {
    id: "pink-bourbon",
    name: "粉波旁",
    nameEn: "Pink Bourbon",
    category: "floral",
    origins: ["哥倫比亞（惠拉省）"],
    lineage: "紅波旁與黃波旁的自然混種，或衣索比亞原生基因，近年基因研究仍有爭議",
    vendor: { acidity: 8.0, body: 5.0, sweetness: 8.0, floral: 9.0, fruity: 8.5, chocolate: 2.0 },
    user:   { acidity: 7.8, body: 4.8, sweetness: 7.2, floral: 8.5, fruity: 8.0, chocolate: 2.2 },
    vendorNotes: ["玫瑰", "荔枝", "黃桃", "花蜜感", "龍眼"],
    userNotes:   ["花香「比藝妓更甜潤不尖銳」是最多人的形容", "日曬版：玫瑰荔枝龍眼，濃郁到論壇直接說「喝完忘不掉」", "水洗版：蜜桃茉莉，結構感更明顯，酸感優雅不刺", "近年價格飛漲，有人說炒作成分多，但真正喝過好批次的人很難反駁"],
  },
  {
    id: "yellow-bourbon",
    name: "黃波旁",
    nameEn: "Yellow Bourbon",
    category: "sweet",
    origins: ["巴西", "薩爾瓦多"],
    lineage: "波旁突變種（果實成熟時呈黃色），巴西為主要產地",
    vendor: { acidity: 6.0, body: 6.5, sweetness: 8.0, floral: 4.5, fruity: 6.0, chocolate: 5.5 },
    user:   { acidity: 5.8, body: 6.0, sweetness: 7.5, floral: 4.0, fruity: 5.5, chocolate: 6.0 },
    vendorNotes: ["焦糖", "蜂蜜", "杏桃", "奶油", "溫和甜感"],
    userNotes:   ["比紅波旁更甜更圓潤", "巴西日曬很香", "甜感是真的", "喝起來很放鬆"],
  },
  {
    id: "sidra",
    name: "西德拉",
    nameEn: "Sidra",
    category: "floral",
    origins: ["厄瓜多", "哥倫比亞"],
    lineage: "確切血統有爭議，可能為鐵比卡 × 衣索比亞原生種，或波旁系衍生",
    vendor: { acidity: 8.5, body: 5.0, sweetness: 8.5, floral: 9.0, fruity: 9.0, chocolate: 1.5 },
    user:   { acidity: 8.2, body: 4.8, sweetness: 7.8, floral: 8.8, fruity: 8.5, chocolate: 1.8 },
    vendorNotes: ["百香果", "茉莉花", "覆盆子", "龍眼蜜", "熱帶花香"],
    userNotes:   ["2019年世界咖啡師大賽冠軍 Jooyeon Jeon 用這支拿冠，論壇因此爆紅", "「荔枝西瓜百香果交疊，甜而不膩」是最多人引用的形容", "哥倫比亞 La Palma 農場批次：在杯測評分上「大幅超越其他新品種」", "價格近年暴漲，有人說「早買早享受，現在好批次搶不到」"],
  },
  {
    id: "maracaturra",
    name: "瑪拉卡杜拉",
    nameEn: "Maracaturra",
    category: "fruity",
    origins: ["尼加拉瓜", "瓜地馬拉"],
    lineage: "象豆（Maragogipe） × 卡杜拉，兼具大豆粒與高酸特性",
    vendor: { acidity: 7.5, body: 5.5, sweetness: 6.5, floral: 5.5, fruity: 7.5, chocolate: 3.0 },
    user:   { acidity: 7.2, body: 5.0, sweetness: 6.0, floral: 5.0, fruity: 7.0, chocolate: 3.5 },
    vendorNotes: ["熱帶水果", "柑橘", "蜂蜜", "清爽酸質"],
    userNotes:   ["豆子大很好辨認", "酸感比象豆乾淨多了", "果香明顯", "比卡杜拉有個性"],
  },
  {
    id: "catimor",
    name: "卡帝摩",
    nameEn: "Catimor",
    category: "bold",
    origins: ["葡萄牙（育種）", "中南美洲", "亞洲廣泛"],
    lineage: "帝汶混血 × 卡杜拉，1959年葡萄牙培育，極抗銹病，羅豆血統佔25%",
    vendor: { acidity: 6.0, body: 7.0, sweetness: 5.5, floral: 2.5, fruity: 4.5, chocolate: 6.5 },
    user:   { acidity: 6.5, body: 7.0, sweetness: 4.5, floral: 2.0, fruity: 4.0, chocolate: 6.0 },
    vendorNotes: ["黑巧克力", "堅果", "厚重body", "低調酸質"],
    userNotes:   ["有明顯的土腥感和羅豆基調，淺焙試過的人幾乎都說「不行」", "深焙後巧克力堅果感出來，但很難說是精品咖啡的體驗", "在東南亞和中美洲大量種植，便宜豆包常見身影", "為了抗銹病犧牲了風味，是業界爭議最大的品種之一"],
  },
  {
    id: "sarchimor",
    name: "薩奇摩",
    nameEn: "Sarchimor",
    category: "balanced",
    origins: ["哥斯大黎加", "巴西", "印度"],
    lineage: "帝汶混血 × 薇拉薩奇，1985年哥斯大黎加 CATIE 培育，耐銹病",
    vendor: { acidity: 7.0, body: 5.5, sweetness: 6.5, floral: 4.5, fruity: 6.0, chocolate: 4.5 },
    user:   { acidity: 6.8, body: 5.3, sweetness: 5.8, floral: 4.0, fruity: 5.5, chocolate: 5.0 },
    vendorNotes: ["桃子", "蜂蜜", "輕盈花香", "乾淨酸質"],
    userNotes:   ["比卡帝摩乾淨很多", "哥斯大黎加蜜處理很香", "不輸波旁的均衡感", "潛力被低估"],
  },
  {
    id: "ruiru11",
    name: "盧伊魯11",
    nameEn: "Ruiru 11",
    category: "bold",
    origins: ["肯亞"],
    lineage: "多重雜交（含 SL28、Hibrido de Timor、Catimor、N39 等），1985年肯亞研究站培育",
    vendor: { acidity: 7.5, body: 7.0, sweetness: 6.0, floral: 4.0, fruity: 6.5, chocolate: 5.5 },
    user:   { acidity: 7.8, body: 7.0, sweetness: 5.2, floral: 3.5, fruity: 6.0, chocolate: 5.8 },
    vendorNotes: ["黑醋栗", "深色莓果", "厚實body", "強烈酸質"],
    userNotes:   ["比SL28更粗獷", "肯亞豆中的強壯派", "有點羅豆感", "義式效果不錯"],
  },
  {
    id: "batian",
    name: "巴提安",
    nameEn: "Batian",
    category: "fruity",
    origins: ["肯亞"],
    lineage: "多重雜交（含 SL28、SL34、Ruiru 11 血統），2010年肯亞最新選育品種",
    vendor: { acidity: 8.0, body: 6.5, sweetness: 6.5, floral: 5.0, fruity: 7.5, chocolate: 4.5 },
    user:   { acidity: 7.8, body: 6.2, sweetness: 6.0, floral: 4.5, fruity: 7.0, chocolate: 5.0 },
    vendorNotes: ["黑莓", "柚子", "磷酸感", "複雜果酸"],
    userNotes:   ["SL28的年輕版", "抗病但風味沒SL差", "高海拔批次很驚豔", "值得更多關注"],
  },
  {
    id: "blue-mountain",
    name: "藍山",
    nameEn: "Blue Mountain",
    category: "balanced",
    origins: ["牙買加", "巴布亞新幾內亞", "肯亞"],
    lineage: "鐵比卡系選育，18世紀英國引入牙買加藍山地區，現為地理保護品種",
    vendor: { acidity: 5.5, body: 6.5, sweetness: 7.0, floral: 5.0, fruity: 5.0, chocolate: 5.5 },
    user:   { acidity: 5.2, body: 6.0, sweetness: 6.2, floral: 4.2, fruity: 4.5, chocolate: 5.8 },
    vendorNotes: ["奶油感", "溫和花香", "輕柔甜感", "無瑕疵乾淨感"],
    userNotes:   ["「名氣和定價遠超過實際風味體驗」是r/Coffee最常見的評語", "乾淨優雅是真的，但論壇普遍覺得「為這個付那個價格不值得」", "適合喜歡低調、不愛強烈酸感的人，是長輩最常誇的咖啡之一", "Papua New Guinea 藍山系統批次評價比牙買加本身還要高，但品牌效應還是在牙買加"],
  },
  {
    id: "tabi",
    name: "塔比",
    nameEn: "Tabi",
    category: "floral",
    origins: ["哥倫比亞"],
    lineage: "鐵比卡 × 帝汶混血 × 波旁，2002年哥倫比亞 CENICAFÉ 培育",
    vendor: { acidity: 7.5, body: 5.5, sweetness: 7.5, floral: 7.5, fruity: 7.0, chocolate: 3.0 },
    user:   { acidity: 7.2, body: 5.2, sweetness: 7.0, floral: 7.0, fruity: 6.5, chocolate: 3.5 },
    vendorNotes: ["茉莉花", "熱帶水果", "蜂蜜", "細緻酸質"],
    userNotes:   ["哥倫比亞的隱藏版", "比卡斯提優有個性", "花香明顯", "罕見但值得找"],
  },
  {
    id: "obata",
    name: "歐巴塔",
    nameEn: "Obatã",
    category: "balanced",
    origins: ["巴西"],
    lineage: "帝汶混血 × 薇拉薩奇，再 × 黃波旁，IAC 巴西農研所選育，耐銹病",
    vendor: { acidity: 6.5, body: 6.5, sweetness: 6.5, floral: 4.0, fruity: 5.5, chocolate: 6.0 },
    user:   { acidity: 6.2, body: 6.2, sweetness: 6.0, floral: 3.5, fruity: 5.0, chocolate: 6.5 },
    vendorNotes: ["焦糖", "牛奶巧克力", "輕微果酸", "均衡厚實"],
    userNotes:   ["巴西精品莊園常見", "可靠穩定不出錯", "比新世界更活潑", "義式蠻好用"],
  },
  {
    id: "timor-hybrid",
    name: "帝汶混血",
    nameEn: "Timor Hybrid (HDT)",
    category: "bold",
    origins: ["東帝汶", "印尼"],
    lineage: "阿拉比卡與羅布斯塔自然雜交，1927年東帝汶發現，是眾多抗病品種的親本",
    vendor: { acidity: 5.0, body: 7.5, sweetness: 5.0, floral: 2.0, fruity: 3.5, chocolate: 7.0 },
    user:   { acidity: 5.5, body: 7.5, sweetness: 4.0, floral: 1.8, fruity: 3.0, chocolate: 7.5 },
    vendorNotes: ["泥土感", "黑巧克力", "厚重body", "低調風味"],
    userNotes:   ["明顯的羅豆感", "不適合淺焙", "深焙還行", "是很多品種的親本但本身不討喜"],
  },
  {
    id: "marsellesa",
    name: "馬賽雷薩",
    nameEn: "Marsellesa",
    category: "balanced",
    origins: ["中美洲（尼加拉瓜、宏都拉斯）"],
    lineage: "薩奇摩衍生系，法國 CIRAD 研發，高抗銹病且杯測表現接近阿拉比卡",
    vendor: { acidity: 7.0, body: 6.0, sweetness: 6.5, floral: 5.0, fruity: 6.0, chocolate: 4.5 },
    user:   { acidity: 6.8, body: 5.8, sweetness: 6.0, floral: 4.5, fruity: 5.5, chocolate: 5.0 },
    vendorNotes: ["桃子", "焦糖甜", "花香尾韻", "乾淨酸質"],
    userNotes:   ["抗病品種裡最好喝的之一", "超越卡帝摩很多", "值得推廣", "中美洲優質莊園在用"],
  },
  {
    id: "harrar",
    name: "哈拉爾",
    nameEn: "Harrar",
    category: "fruity",
    origins: ["衣索比亞（哈拉爾地區）"],
    lineage: "衣索比亞東部高地原生品種，幾乎全為日曬處理，品種基因多樣",
    vendor: { acidity: 7.5, body: 5.0, sweetness: 7.0, floral: 6.0, fruity: 8.5, chocolate: 3.0 },
    user:   { acidity: 7.2, body: 5.0, sweetness: 6.5, floral: 5.5, fruity: 8.0, chocolate: 3.5 },
    vendorNotes: ["藍莓", "野生莓果", "葡萄酒感", "發酵果香"],
    userNotes:   ["幾乎全日曬，「野莓藍莓葡萄酒發酵感，不像任何其他衣索比亞」", "有人愛極了那個狂野發酵果香，有人說「像爛水果，受不了」", "真正的老哈拉爾批次（非工業化後的）據說是傳說中的咖啡", "近年品質不穩，要找信任的烘豆師才能買到好批次"],
  },
];

export const CATEGORY_LABELS: Record<FlavorCategory, string> = {
  floral:     "花香型",
  fruity:     "果香型",
  sweet:      "甜感型",
  chocolate:  "巧克力型",
  balanced:   "均衡型",
  bold:       "強勁型",
};

export const CATEGORY_COLORS: Record<FlavorCategory, string> = {
  floral:    "#e879f9",
  fruity:    "#fb923c",
  sweet:     "#fbbf24",
  chocolate: "#a16207",
  balanced:  "#2dd4bf",
  bold:      "#3b5bdb",
};

export const FLAVOR_DIMS = [
  { key: "acidity",   label: "酸度" },
  { key: "body",      label: "醇厚度" },
  { key: "sweetness", label: "甜感" },
  { key: "floral",    label: "花香" },
  { key: "fruity",    label: "果香" },
  { key: "chocolate", label: "可可/堅果" },
] as const;

export type FlavorDimKey = typeof FLAVOR_DIMS[number]["key"];
