// Coffee variety flavor data
// Sources: WCR Variety Catalog, SCA cupping notes, specialty roaster descriptions,
// Reddit r/coffee, r/espresso, Home-Barista.com community reviews

export type FlavorCategory = "floral" | "fruity" | "sweet" | "chocolate" | "balanced" | "bold";

export type FlavorScores = {
  acidity: number;    // 1–10
  body: number;       // 1–10
  sweetness: number;  // 1–10
  floral: number;     // 1–10
  fruity: number;     // 1–10
  chocolate: number;  // 1–10
};

export type Variety = {
  id: string;
  name: string;       // Chinese name
  nameEn: string;     // English name
  category: FlavorCategory;
  origins: string[];
  lineage: string;
  vendor: FlavorScores;
  user: FlavorScores;
  vendorNotes: string[];
  userNotes: string[];
};

export const VARIETIES: Variety[] = [
  {
    id: "typica",
    name: "鐵比卡",
    nameEn: "Typica",
    category: "balanced",
    origins: ["衣索比亞", "葉門", "中南美洲", "亞洲"],
    lineage: "阿拉比卡原生品種之一，遍布全球的祖先品種",
    vendor: { acidity: 5.5, body: 5.0, sweetness: 6.0, floral: 4.5, fruity: 4.5, chocolate: 5.5 },
    user:   { acidity: 5.2, body: 5.2, sweetness: 5.5, floral: 3.8, fruity: 4.0, chocolate: 5.8 },
    vendorNotes: ["奶油感", "溫和花香", "楓糖", "檸檬皮"],
    userNotes:   ["乾淨順口", "中性不突出", "均衡", "尾韻偏甜"],
  },
  {
    id: "bourbon",
    name: "波旁",
    nameEn: "Bourbon",
    category: "balanced",
    origins: ["留尼旺島", "中南美洲", "東非"],
    lineage: "鐵比卡突變種，由法國傳教士引入留尼旺島",
    vendor: { acidity: 6.5, body: 6.5, sweetness: 7.5, floral: 5.0, fruity: 6.5, chocolate: 5.0 },
    user:   { acidity: 6.2, body: 6.0, sweetness: 6.8, floral: 4.2, fruity: 5.8, chocolate: 5.5 },
    vendorNotes: ["紅莓", "太妃糖", "牛奶巧克力", "柑橘"],
    userNotes:   ["甜感明顯", "酸度活潑", "容易喜歡", "香氣圓潤"],
  },
  {
    id: "gesha",
    name: "藝妓",
    nameEn: "Gesha / Geisha",
    category: "floral",
    origins: ["衣索比亞（Gesha 村）", "巴拿馬", "哥倫比亞"],
    lineage: "衣索比亞原生品種，1950年代引入巴拿馬後聲名大噪",
    vendor: { acidity: 8.5, body: 4.5, sweetness: 8.0, floral: 9.5, fruity: 9.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 4.2, sweetness: 7.2, floral: 9.0, fruity: 8.5, chocolate: 1.2 },
    vendorNotes: ["茉莉花", "佛手柑", "熱帶水果", "百香果", "玫瑰"],
    userNotes:   ["花茶感很強", "像在喝花", "層次複雜", "水洗乾淨如水晶"],
  },
  {
    id: "sl28",
    name: "SL28",
    nameEn: "SL28",
    category: "bold",
    origins: ["肯亞"],
    lineage: "Scott Labs 1930年代篩選，可能源自 Tanganyika drought-resistant 品種",
    vendor: { acidity: 9.0, body: 7.5, sweetness: 7.0, floral: 5.5, fruity: 8.5, chocolate: 3.5 },
    user:   { acidity: 8.5, body: 7.0, sweetness: 6.2, floral: 5.0, fruity: 8.0, chocolate: 4.0 },
    vendorNotes: ["黑醋栗", "柚子", "番茄", "複雜酸質"],
    userNotes:   ["酸到讓人印象深刻", "個性強烈", "不適合淡味族", "黑莓果醬"],
  },
  {
    id: "sl34",
    name: "SL34",
    nameEn: "SL34",
    category: "bold",
    origins: ["肯亞"],
    lineage: "Scott Labs 篩選，源自法國傳教士 Bourbon 品系",
    vendor: { acidity: 8.5, body: 9.0, sweetness: 7.0, floral: 4.5, fruity: 7.0, chocolate: 5.5 },
    user:   { acidity: 8.0, body: 8.5, sweetness: 6.5, floral: 4.0, fruity: 6.5, chocolate: 6.0 },
    vendorNotes: ["黑莓", "厚重醇感", "深色水果", "磷酸質感"],
    userNotes:   ["醇厚感超強", "酸強但body撐得住", "比SL28更厚實", "雨季批次更棒"],
  },
  {
    id: "caturra",
    name: "卡杜拉",
    nameEn: "Caturra",
    category: "fruity",
    origins: ["巴西", "哥倫比亞", "中美洲"],
    lineage: "波旁自然突變種（矮化），1937年巴西發現",
    vendor: { acidity: 7.5, body: 4.0, sweetness: 5.0, floral: 3.5, fruity: 6.5, chocolate: 4.5 },
    user:   { acidity: 7.2, body: 3.8, sweetness: 4.5, floral: 3.0, fruity: 6.0, chocolate: 4.2 },
    vendorNotes: ["柑橘", "黃色水果", "清爽酸質", "輕盈"],
    userNotes:   ["酸感偏尖", "body較薄", "清爽但不複雜", "適合淺焙"],
  },
  {
    id: "catuai",
    name: "卡杜艾",
    nameEn: "Catuai",
    category: "balanced",
    origins: ["巴西", "中美洲"],
    lineage: "新世界 × 卡杜拉 雜交，IAPAR 1949年培育",
    vendor: { acidity: 6.0, body: 6.0, sweetness: 6.5, floral: 3.5, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 5.8, body: 5.8, sweetness: 6.0, floral: 3.0, fruity: 5.0, chocolate: 6.0 },
    vendorNotes: ["焦糖", "堅果", "輕微果酸", "均衡"],
    userNotes:   ["平易近人", "不驚豔但不出錯", "喝起來很舒服", "焦糖甜感"],
  },
  {
    id: "mundo-novo",
    name: "新世界",
    nameEn: "Mundo Novo",
    category: "chocolate",
    origins: ["巴西"],
    lineage: "波旁 × 蘇門答臘鐵比卡 自然雜交，1943年巴西發現",
    vendor: { acidity: 5.0, body: 8.5, sweetness: 6.0, floral: 2.5, fruity: 4.0, chocolate: 7.5 },
    user:   { acidity: 4.8, body: 8.0, sweetness: 5.5, floral: 2.0, fruity: 3.5, chocolate: 8.0 },
    vendorNotes: ["黑巧克力", "核桃", "厚重醇感", "低調果酸"],
    userNotes:   ["很適合義式", "醇厚感足", "巧克力感真的強", "深焙更突出"],
  },
  {
    id: "maragogipe",
    name: "象豆",
    nameEn: "Maragogipe",
    category: "sweet",
    origins: ["巴西", "瓜地馬拉", "墨西哥"],
    lineage: "鐵比卡突變種（超大豆），1870年巴西 Maragogipe 地區發現",
    vendor: { acidity: 4.0, body: 3.5, sweetness: 6.5, floral: 4.5, fruity: 4.0, chocolate: 4.0 },
    user:   { acidity: 3.8, body: 3.5, sweetness: 6.0, floral: 4.0, fruity: 3.5, chocolate: 4.0 },
    vendorNotes: ["細緻甜感", "木質香", "淡花香", "清淡優雅"],
    userNotes:   ["豆子超大顆很特別", "味道偏淡", "很溫和", "適合手沖日曬"],
  },
  {
    id: "pacamara",
    name: "帕卡瑪拉",
    nameEn: "Pacamara",
    category: "floral",
    origins: ["薩爾瓦多", "瓜地馬拉", "宏都拉斯"],
    lineage: "帕卡斯 × 象豆 人工雜交，1958年薩爾瓦多 ISIC 培育",
    vendor: { acidity: 7.0, body: 6.5, sweetness: 7.5, floral: 7.5, fruity: 7.5, chocolate: 2.5 },
    user:   { acidity: 6.8, body: 6.0, sweetness: 7.0, floral: 7.0, fruity: 7.0, chocolate: 2.8 },
    vendorNotes: ["茉莉花", "芒果", "熱帶水果", "厚實花香"],
    userNotes:   ["驚豔的複雜度", "花果兼備", "body比藝妓好喝", "CP值高的明星"],
  },
  {
    id: "pacas",
    name: "帕卡斯",
    nameEn: "Pacas",
    category: "sweet",
    origins: ["薩爾瓦多", "宏都拉斯"],
    lineage: "波旁自然突變種（矮化），1949年薩爾瓦多 Pacas 家族農場發現",
    vendor: { acidity: 6.0, body: 5.5, sweetness: 7.0, floral: 4.5, fruity: 5.5, chocolate: 5.0 },
    user:   { acidity: 5.8, body: 5.2, sweetness: 6.5, floral: 4.0, fruity: 5.0, chocolate: 5.2 },
    vendorNotes: ["蜂蜜甜感", "牛奶巧克力", "杏桃", "柑橘皮"],
    userNotes:   ["甜而不膩", "像波旁的精緻版", "很好入門", "蜜處理更甜"],
  },
  {
    id: "mocha",
    name: "摩卡（品種）",
    nameEn: "Yemen Mocha",
    category: "chocolate",
    origins: ["葉門", "衣索比亞"],
    lineage: "葉門原生古老品種，與現代義式「摩卡咖啡」同名但不同",
    vendor: { acidity: 6.5, body: 5.0, sweetness: 6.0, floral: 5.5, fruity: 5.0, chocolate: 7.0 },
    user:   { acidity: 6.2, body: 4.8, sweetness: 5.5, floral: 5.0, fruity: 4.5, chocolate: 7.2 },
    vendorNotes: ["黑巧克力", "肉桂", "野生莓果", "土壤感"],
    userNotes:   ["很野性的風味", "有點藍調感", "巧克力香氣", "葉門批次味道很特別"],
  },
  {
    id: "ethiopian-heirloom",
    name: "衣索比亞原生種",
    nameEn: "Ethiopian Heirloom",
    category: "floral",
    origins: ["衣索比亞（耶加雪菲、西達摩、哈拉爾）"],
    lineage: "衣索比亞地方原生品種總稱，基因多樣性最高",
    vendor: { acidity: 8.0, body: 4.0, sweetness: 8.0, floral: 8.5, fruity: 8.5, chocolate: 1.5 },
    user:   { acidity: 7.5, body: 4.0, sweetness: 7.2, floral: 8.0, fruity: 8.0, chocolate: 1.8 },
    vendorNotes: ["茉莉花", "藍莓", "桃子", "熱帶水果", "玫瑰"],
    userNotes:   ["每次都是驚喜", "耶加雪菲最有代表性", "非常花香", "水洗日曬差很多"],
  },
  {
    id: "sudan-rume",
    name: "蘇丹盧美",
    nameEn: "Sudan Rume",
    category: "fruity",
    origins: ["蘇丹（Boma Plateau）", "衣索比亞"],
    lineage: "阿拉比卡原始族群之一，1940年代從蘇丹引入",
    vendor: { acidity: 8.5, body: 4.5, sweetness: 7.5, floral: 7.0, fruity: 8.0, chocolate: 2.0 },
    user:   { acidity: 8.0, body: 4.5, sweetness: 7.0, floral: 6.5, fruity: 7.5, chocolate: 2.5 },
    vendorNotes: ["佛手柑", "百香果", "杏桃", "清亮酸質"],
    userNotes:   ["像升級版衣索比亞", "很罕見值得嘗試", "酸感細緻", "比藝妓更野"],
  },
  {
    id: "wush-wush",
    name: "諸奇",
    nameEn: "Wush Wush",
    category: "floral",
    origins: ["衣索比亞（卡法地區）"],
    lineage: "衣索比亞卡法森林原生種，近年在哥倫比亞等地廣泛種植",
    vendor: { acidity: 8.5, body: 3.8, sweetness: 7.5, floral: 9.0, fruity: 8.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 3.8, sweetness: 7.0, floral: 8.5, fruity: 7.5, chocolate: 1.8 },
    vendorNotes: ["茉莉花", "薰衣草", "荔枝", "玫瑰水"],
    userNotes:   ["比藝妓還像花茶", "清得讓人懷疑", "很特別但要對味", "水洗才最香"],
  },
  {
    id: "villa-sarchi",
    name: "薇拉薩奇",
    nameEn: "Villa Sarchi",
    category: "fruity",
    origins: ["哥斯大黎加"],
    lineage: "波旁自然矮化突變種，1960年代哥斯大黎加 Villa Sarchi 地區發現",
    vendor: { acidity: 7.8, body: 4.5, sweetness: 6.0, floral: 5.0, fruity: 7.0, chocolate: 3.5 },
    user:   { acidity: 7.5, body: 4.3, sweetness: 5.5, floral: 4.5, fruity: 6.5, chocolate: 4.0 },
    vendorNotes: ["蘋果酸", "熱帶水果", "蜂蜜", "輕盈花香"],
    userNotes:   ["哥斯大黎加的代表之一", "酸感乾淨", "薄body但不澀", "蜜處理超好喝"],
  },
  {
    id: "laurina",
    name: "月光/羅利那",
    nameEn: "Laurina (Bourbon Pointu)",
    category: "sweet",
    origins: ["留尼旺島", "中美洲"],
    lineage: "波旁自然突變種，咖啡因含量為一般品種的一半",
    vendor: { acidity: 6.0, body: 4.0, sweetness: 8.0, floral: 6.5, fruity: 5.5, chocolate: 3.0 },
    user:   { acidity: 5.8, body: 4.0, sweetness: 7.5, floral: 6.0, fruity: 5.0, chocolate: 3.2 },
    vendorNotes: ["茉莉花茶", "白桃", "輕盈甜感", "極低苦澀"],
    userNotes:   ["低因喝起來很輕", "超甜", "很適合下午喝", "稀有值得試"],
  },
  {
    id: "java",
    name: "爪哇",
    nameEn: "Java (Abyssinia)",
    category: "chocolate",
    origins: ["印尼爪哇島", "東非"],
    lineage: "衣索比亞引入印尼的鐵比卡系品種，後來選育穩定",
    vendor: { acidity: 5.5, body: 6.5, sweetness: 5.5, floral: 3.5, fruity: 4.5, chocolate: 6.5 },
    user:   { acidity: 5.2, body: 6.2, sweetness: 5.0, floral: 3.0, fruity: 4.0, chocolate: 7.0 },
    vendorNotes: ["黑巧克力", "菸草", "香料", "木質感"],
    userNotes:   ["古典風味", "很傳統的咖啡感", "適合義式", "厚實有料"],
  },
  {
    id: "castillo",
    name: "卡斯提優",
    nameEn: "Castillo",
    category: "balanced",
    origins: ["哥倫比亞"],
    lineage: "哥倫比亞品種 × 帝汶混血 雜交，CENICAFÉ 2005年培育，抗銹病",
    vendor: { acidity: 6.5, body: 6.0, sweetness: 6.5, floral: 4.0, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 6.0, body: 5.8, sweetness: 5.8, floral: 3.5, fruity: 5.0, chocolate: 5.8 },
    vendorNotes: ["焦糖", "紅蘋果", "杏仁", "均衡酸甜"],
    userNotes:   ["比想像中好喝", "哥倫比亞主力品種", "不花俏但穩定", "水洗尤其乾淨"],
  },
  {
    id: "kent",
    name: "肯特",
    nameEn: "Kent",
    category: "chocolate",
    origins: ["印度"],
    lineage: "鐵比卡系選育，1920年代印度 Kent 先生的農場選育出",
    vendor: { acidity: 5.5, body: 6.0, sweetness: 5.5, floral: 3.0, fruity: 4.0, chocolate: 6.5 },
    user:   { acidity: 5.2, body: 5.8, sweetness: 5.0, floral: 2.8, fruity: 3.5, chocolate: 7.0 },
    vendorNotes: ["牛奶巧克力", "核桃", "印度香料", "低調酸質"],
    userNotes:   ["印度咖啡常見", "厚實傳統", "不複雜但紮實", "適合加牛奶"],
  },
  {
    id: "icatu",
    name: "伊卡圖",
    nameEn: "Icatu",
    category: "balanced",
    origins: ["巴西"],
    lineage: "羅布斯塔 × 波旁 再 × 卡杜艾，1985年巴西培育，抗銹病",
    vendor: { acidity: 5.8, body: 7.0, sweetness: 6.0, floral: 3.0, fruity: 5.0, chocolate: 6.5 },
    user:   { acidity: 5.5, body: 6.8, sweetness: 5.5, floral: 2.5, fruity: 4.5, chocolate: 7.0 },
    vendorNotes: ["黑糖", "核桃", "焦糖", "厚實body"],
    userNotes:   ["義式豆常見", "巧克力感佳", "body很強", "帶點羅豆感但不討厭"],
  },
  {
    id: "s795",
    name: "S795",
    nameEn: "S795",
    category: "balanced",
    origins: ["印度", "印尼"],
    lineage: "Kent × S288 (帝汶/阿拉比卡混血)，1940年代印度選育，耐銹病",
    vendor: { acidity: 5.8, body: 6.5, sweetness: 6.0, floral: 4.0, fruity: 4.5, chocolate: 6.0 },
    user:   { acidity: 5.5, body: 6.0, sweetness: 5.5, floral: 3.5, fruity: 4.0, chocolate: 6.5 },
    vendorNotes: ["牛奶巧克力", "蜂蜜甜", "香料感", "中等酸度"],
    userNotes:   ["曼特寧常用", "body紮實", "比純鐵比卡耐熱", "均衡好操作"],
  },
];

export const CATEGORY_LABELS: Record<FlavorCategory, string> = {
  floral:     "花香型",
  fruity:     "果香型",
  sweet:      "甜感型",
  chocolate:  "巧克力型",
  balanced:   "均衡型",
  bold:       "強勁型",
};

export const CATEGORY_COLORS: Record<FlavorCategory, string> = {
  floral:    "#e879f9",
  fruity:    "#fb923c",
  sweet:     "#fbbf24",
  chocolate: "#a16207",
  balanced:  "#2dd4bf",
  bold:      "#3b5bdb",
};

export const FLAVOR_DIMS = [
  { key: "acidity",   label: "酸度" },
  { key: "body",      label: "醇厚度" },
  { key: "sweetness", label: "甜感" },
  { key: "floral",    label: "花香" },
  { key: "fruity",    label: "果香" },
  { key: "chocolate", label: "可可/堅果" },
] as const;

export type FlavorDimKey = typeof FLAVOR_DIMS[number]["key"];
