// Coffee variety flavor data
// vendorNotes: WCR Variety Catalog (direct fetch 2026-04-16), CoffeeReview, PerfectDailyGrind,
//   specialty coffee sources (miruscoffee.com, xliiicoffee.com, homegrounds.co, colipsecoffee.com)
// userNotes: r/Coffee, r/espresso, Home-Barista.com, PerfectDailyGrind user comments,
//   CoffeeReview.com taster notes, specialty forum discussions (2020–2025)
// Source reference: app/coffee-guide/data-sources.json

export type FlavorCategory = "floral" | "fruity" | "sweet" | "chocolate" | "balanced" | "bold";

export type FlavorScores = {
  acidity: number;    // 1–10
  body: number;       // 1–10
  sweetness: number;  // 1–10
  floral: number;     // 1–10
  fruity: number;     // 1–10
  chocolate: number;  // 1–10
};

export type Variety = {
  id: string;
  name: string;       // Chinese name
  nameEn: string;     // English name
  category: FlavorCategory;
  origins: string[];
  lineage: string;
  vendor: FlavorScores;
  user: FlavorScores;
  vendorNotes: string[];
  userNotes: string[];
};

export const VARIETIES: Variety[] = [
  {
    id: "typica",
    name: "鐵比卡",
    nameEn: "Typica",
    category: "balanced",
    origins: ["衣索比亞", "葉門", "中南美洲", "亞洲"],
    lineage: "Bourbon-Typica group (Typica related)。原產衣索比亞，15-16世紀傳至葉門，1696-1699年傳至印尼爪哇，後散布全球。別名：Criollo、Blue Mountain、Sumatra",
    vendor: { acidity: 5.5, body: 5.5, sweetness: 6.0, floral: 4.5, fruity: 4.5, chocolate: 5.5 },
    user:   { acidity: 5.2, body: 5.2, sweetness: 5.5, floral: 3.8, fruity: 4.0, chocolate: 5.8 },
    vendorNotes: ["清新平衡花香（specialty: clean, balanced, aromatic）", "楓糖焦糖尾韻（specialty: caramel, maple）", "溫和酸質（medium acidity）", "輕微堅果巧克力感（specialty: nutty, chocolate hint）"],
    userNotes:   ["「這就是阿拉比卡的原型，乾淨甜潤無雜味，是理解其他品種的基準線」——反覆出現在論壇推薦入門的帖子裡（specialty community）", "水洗版清澈如水，日曬版意外多了花果層次；同樣品種在不同產區可以差距很大（r/Coffee）", "PDG 評語：「elegance, flowers and fruits」——低調不搶眼，但拿來比較其他品種時才看出精緻（PDG）", "爪哇和蘇門答臘批次加上濕刨法完全改頭換面，「地球上最多元的單一品種」一點不誇張（r/Coffee）"],
  },
  {
    id: "bourbon",
    name: "波旁",
    nameEn: "Bourbon",
    category: "balanced",
    origins: ["留尼旺島", "中南美洲", "東非"],
    lineage: "Bourbon-Typica group (Bourbon related)。法國傳教士18世紀初從葉門引入留尼旺島，1860年前後傳至巴西，再散布中南美洲",
    vendor: { acidity: 6.5, body: 6.5, sweetness: 7.5, floral: 4.5, fruity: 6.5, chocolate: 5.5 },
    user:   { acidity: 6.2, body: 6.0, sweetness: 6.8, floral: 4.2, fruity: 5.8, chocolate: 5.5 },
    vendorNotes: ["焦糖莓果甜香（CoffeeReview: caramel, red berries）", "牛奶巧克力尾韻（specialty: milk chocolate）", "桃子石果果酸（specialty: stone fruit）", "紮實圓潤醇感（specialty: full-bodied, smooth）"],
    userNotes:   ["紅波旁：絲滑醇厚，牛軋糖奶油巧克力交疊，甜感讓人直覺說「再來一杯」（r/Coffee）", "黃波旁甜度爆表，杏桃香蕉熱帶果，有人說這才是「喝得出甜的咖啡」（r/Coffee）", "高海拔薩爾瓦多批次常見莓果複雜度，蜜處理後太妃糖感更突出，是論壇推薦入門精品的首選（r/espresso）", "「同樣叫波旁，不同產地風味可以差很遠」——肯亞波旁酸、盧安達波旁甜、薩爾瓦多波旁醇，一定要標注產地（r/Coffee）"],
  },
  {
    id: "gesha",
    name: "藝妓",
    nameEn: "Gesha / Geisha",
    category: "floral",
    origins: ["衣索比亞（Gesha 村）", "巴拿馬", "哥倫比亞"],
    lineage: "衣索比亞森林原生種（Ethiopian landrace），1930年代採集，傳至坦桑尼亞Lyamungu站，1953年由CATIE收錄為T2722，1960年代傳至巴拿馬各農場",
    vendor: { acidity: 8.5, body: 4.0, sweetness: 8.0, floral: 9.5, fruity: 9.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 4.2, sweetness: 7.2, floral: 9.0, fruity: 8.5, chocolate: 1.2 },
    vendorNotes: ["茉莉花（WCR: jasmine）", "佛手柑（WCR: bergamot）", "熱帶水果（specialty: papaya, guava, mango）", "桃子與白茶感（WCR: peach, tea-like body）"],
    userNotes:   ["烘焙時飄藍莓香，研磨時是佛手柑，入杯後變成伯爵茶——每個階段都是不同驚喜（specialty community）", "Esmeralda批次：莓果柑橘芒果番石榴層疊，喝過的人說再也喝不了普通咖啡（r/Coffee）", "冷卻後酸感才出來，有人說「放到微溫才到達完全體」，熱喝會錯過一半（r/Coffee）", "論壇兩極：「改變了對咖啡的認知」vs「不值那個價」——高海拔頂批次才能回答這個問題（r/espresso）"],
  },
  {
    id: "sl28",
    name: "SL28",
    nameEn: "SL28",
    category: "fruity",
    origins: ["肯亞"],
    lineage: "Bourbon-Typica group (Bourbon related)。1935年肯亞Scott Labs從Tanganyika Drought Resistant品系選育，基因測試確認與Bourbon群相近",
    vendor: { acidity: 9.0, body: 7.0, sweetness: 6.5, floral: 5.0, fruity: 8.5, chocolate: 3.0 },
    user:   { acidity: 8.5, body: 7.0, sweetness: 6.2, floral: 5.0, fruity: 8.0, chocolate: 4.0 },
    vendorNotes: ["黑醋栗（PDG: blackcurrant）", "磷酸酸質（CoffeeReview: phosphoric acidity）", "夏日番茄甜酸（specialty: fresh tomato）", "野生覆盆子柑橘（CoffeeReview: wild raspberry, citrus）"],
    userNotes:   ["CoffeeReview評94分：油桃水仙花、Meyer檸檬皮、牛軋糖——「juicy, deep, balanced, bright」，肯亞風土的完美表達（CoffeeReview）", "黑莓覆盆子混著鮮甜番茄鮮味，有人說這是肯亞豆的「靈魂之味」，第一口就記住了（r/Coffee）", "磷酸酸感真實存在——喝完嘴裡電流感好幾分鐘不散，不習慣的人會嚇到，習慣了就上癮（Home-Barista）", "好批次的「夏日番茄＋黑醋栗」甜酸交疊是高辨識度體驗，論壇說：「這就是為什麼肯亞豆有死忠粉」（r/Coffee）"],
  },
  {
    id: "sl34",
    name: "SL34",
    nameEn: "SL34",
    category: "balanced",
    origins: ["肯亞"],
    lineage: "Bourbon-Typica group（Typica related，非Bourbon）。1935-1939年肯亞Loresho莊園French Mission標記樹選育，基因測試實際為Typica血統而非Bourbon",
    vendor: { acidity: 8.5, body: 8.5, sweetness: 6.5, floral: 4.0, fruity: 7.5, chocolate: 5.0 },
    user:   { acidity: 8.0, body: 8.5, sweetness: 6.5, floral: 4.0, fruity: 6.5, chocolate: 6.0 },
    vendorNotes: ["黑莓深色水果（specialty: blackberry, dark fruit）", "厚實圓潤醇感（specialty: very full body）", "複雜甜酸（specialty: complex acidity with caramel aftertaste）", "熱帶水果醋栗（specialty: tropical, currant）"],
    userNotes:   ["和SL28一起出現在頂批時，論壇說「兩者加在一起才是完整的肯亞」——SL28負責酸、SL34負責body（r/Coffee）", "「磷酸感沒SL28強，但醇厚度遠超它，喝起來有豐滿的葡萄酒感」是最高辨識度評語（r/Coffee）", "深色莓果果醬加焦糖，比SL28更圓潤，有人說「SL28是明星，SL34是定海神針」（specialty community）", "在肯亞頂批常被低估，因為SL28的名氣太大；但盲測時常有人更喜歡SL34（Home-Barista）"],
  },
  {
    id: "caturra",
    name: "卡杜拉",
    nameEn: "Caturra",
    category: "balanced",
    origins: ["巴西", "哥倫比亞", "中美洲"],
    lineage: "Bourbon-Typica group (Bourbon related)。波旁自然突變種（矮化），1915-1918年巴西米納斯吉拉斯州發現，1937年IAC開始選育",
    vendor: { acidity: 7.5, body: 4.0, sweetness: 5.5, floral: 3.5, fruity: 6.5, chocolate: 4.0 },
    user:   { acidity: 7.2, body: 3.8, sweetness: 4.5, floral: 3.0, fruity: 6.0, chocolate: 4.2 },
    vendorNotes: ["柑橘明亮酸質（specialty: citrus, bright acidity）", "黃色水果（specialty: yellow fruit）", "清爽輕盈（specialty: clean, light）", "楓糖蜂蜜香氣（specialty: maple, honey aroma）"],
    userNotes:   ["CoffeeReview 頂批可達90分，但平均批次的「水感」被論壇反覆提到——海拔差距決定一切（CoffeeReview）", "「哥倫比亞水洗版明亮乾淨但body薄；換成哥斯大黎加蜜處理就多了甜感層次，同品種兩個世界」（r/Coffee）", "高海拔柑橘酸感精準明亮，低海拔則「就是普通商業豆水準，買貴了才會失望」（r/Coffee）", "論壇推薦的「親民入門品種」——價格合理、風味輪廓清楚，適合正在建立味覺基準的人（specialty community）"],
  },
  {
    id: "catuai",
    name: "卡杜艾",
    nameEn: "Catuai",
    category: "balanced",
    origins: ["巴西", "中美洲"],
    lineage: "Bourbon-Typica group (Typica and Bourbon related)。新世界 × 卡杜拉，IAC（Instituto Agronômico）巴西1949年培育，原稱H-2077，1972年發布",
    vendor: { acidity: 6.0, body: 6.0, sweetness: 7.0, floral: 3.5, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 5.8, body: 5.8, sweetness: 6.0, floral: 3.0, fruity: 5.0, chocolate: 6.0 },
    vendorNotes: ["巧克力焦糖（specialty: chocolate, caramel）", "蜂蜜杏仁（specialty: honey, almond）", "輕微柑橘果酸（specialty: gentle citrus）", "均衡甜感（specialty: balanced sweetness）"],
    userNotes:   ["「高海拔瓜地馬拉卡杜艾有真正的明亮果酸，低海拔版本卻平到讓人懷疑是不是同品種」（r/Coffee）", "黃卡杜艾比紅版更甜更花香，論壇有人說「兩者盲測根本以為是不同品種」——顏色突變影響風味（r/Coffee）", "巴西商業批次主力，義式配方穩定骨幹——「不驚豔但不出錯，反覆用了十年」（specialty community）", "Sweet Maria's 說它是「懂得妥協的品種」——為生產效率和風味之間取得折衷，是全球種植最廣的阿拉比卡之一（Sweet Maria's）"],
  },
  {
    id: "mundo-novo",
    name: "新世界",
    nameEn: "Mundo Novo",
    category: "chocolate",
    origins: ["巴西"],
    lineage: "Bourbon-Typica group (Typica and Bourbon related)。波旁 × 鐵比卡自然雜交，1943年巴西聖保羅州Mineiros do Tiete發現",
    vendor: { acidity: 5.0, body: 8.5, sweetness: 6.0, floral: 2.5, fruity: 4.0, chocolate: 7.5 },
    user:   { acidity: 4.8, body: 8.0, sweetness: 5.5, floral: 2.0, fruity: 3.5, chocolate: 8.0 },
    vendorNotes: ["黑巧克力（specialty: dark chocolate）", "乾果甜香（specialty: dried fruit）", "厚重醇感（WCR: very full body）", "柑橘尾韻（specialty: citric finish）"],
    userNotes:   ["義式配方烘豆師最愛之一：「比新世界更厚的body你找不到，奶泡融合後甜感加倍」（specialty community）", "深焙後核桃巧克力感極強，被形容「老派好喝、低技術門檻的正確選擇」（r/Coffee）", "低酸高body，不喜歡果酸者的心頭好，有人說「這是我媽願意喝的第一支精品豆」（r/espresso）", "日曬版意外多了深色果乾感，「乾燥無花果加巧克力，喝完嘴裡甜甜的」——加分項（r/Coffee）"],
  },
  {
    id: "maragogipe",
    name: "象豆",
    nameEn: "Maragogipe",
    category: "balanced",
    origins: ["巴西", "瓜地馬拉", "墨西哥"],
    lineage: "Bourbon-Typica group (Typica related)。鐵比卡自然突變種，單一顯性基因造成超大豆粒，1870年巴西Maragogipe市發現",
    vendor: { acidity: 4.0, body: 3.5, sweetness: 7.0, floral: 4.5, fruity: 4.0, chocolate: 4.0 },
    user:   { acidity: 3.8, body: 3.5, sweetness: 6.0, floral: 4.0, fruity: 3.5, chocolate: 4.0 },
    vendorNotes: ["細緻甜感（WCR: good to very good quality）", "優雅木質香（specialty: woody, elegant）", "超大豆粒（WCR: very large bean size）", "品質批次差異大（specialty: notoriously inconsistent）"],
    userNotes:   ["「豆子巨大、孔隙率高，用同樣參數萃取一定萃不足——要調整研磨和水溫才能拉出甜感」（Home-Barista）", "好批次甜潤優雅帶木質感；差批次水薄無味；論壇共識是「信任烘豆師比選品種更重要」（r/Coffee）", "「像被放大的鐵比卡，把優點和缺點都放大了」——好批次極好，差批次讓人搞不清楚在喝什麼（r/Coffee）", "瓜地馬拉和墨西哥高海拔批次被認為最容易找到好品質，尼加拉瓜也有不錯紀錄（specialty community）"],
  },
  {
    id: "pacamara",
    name: "帕卡瑪拉",
    nameEn: "Pacamara",
    category: "balanced",
    origins: ["薩爾瓦多", "瓜地馬拉", "宏都拉斯"],
    lineage: "Bourbon-Typica group (Typica and Bourbon related)。帕卡斯 × 象豆人工雜交，1958年薩爾瓦多ISIC培育，植株不穩定（非均質）",
    vendor: { acidity: 7.5, body: 7.0, sweetness: 7.0, floral: 5.0, fruity: 7.5, chocolate: 5.5 },
    user:   { acidity: 6.5, body: 7.0, sweetness: 6.5, floral: 4.0, fruity: 6.5, chocolate: 5.8 },
    vendorNotes: ["桃子石果（specialty: peach, stone fruit）", "奶油焦糖（specialty: caramel, butter）", "茉莉偶現（WCR: jasmine at high altitude）", "豐厚醇感（WCR: capable of exceptional quality）"],
    userNotes:   ["好批次：奶油焦糖底加桃子石果，body比多數淺焙豆厚實很多", "差批次：帶蔬菜、蘑菇甚至紙板味，差批次「非常普遍」", "最大特徵是從象豆來的厚重感，不是花香——跟藝妓根本是不同賽道", "Cup of Excellence 常客，高海拔才會偶爾出現花香，但那是加分不是主調"],
  },
  {
    id: "pacas",
    name: "帕卡斯",
    nameEn: "Pacas",
    category: "balanced",
    origins: ["薩爾瓦多", "宏都拉斯"],
    lineage: "Bourbon-Typica group (Bourbon related)。波旁自然突變種（矮化），1949年薩爾瓦多聖安娜地區Pacas家族農場發現，約佔薩爾瓦多25%咖啡產量",
    vendor: { acidity: 6.0, body: 5.5, sweetness: 7.5, floral: 4.5, fruity: 6.0, chocolate: 5.0 },
    user:   { acidity: 5.8, body: 5.2, sweetness: 6.5, floral: 4.0, fruity: 5.0, chocolate: 5.2 },
    vendorNotes: ["焦糖蜂蜜（specialty: caramel, honey）", "牛奶巧克力（specialty: milk chocolate）", "杏桃梅子（specialty: apricot, plum）", "柑橘皮尾韻（specialty: citrus zest finish）"],
    userNotes:   ["波旁的自然矮化突變種，薩爾瓦多最具代表性的品種之一", "甜感比標準波旁更集中，「甜而不膩、喝完想再來一杯」是最常聽到的評語", "蜜處理後杏桃焦糖感更強，水洗版則乾淨清甜，兩者都值得試", "入門精品豆的好選擇，價格合理且風味輪廓清楚"],
  },
  {
    id: "mocha",
    name: "摩卡（品種）",
    nameEn: "Yemen Mocha",
    category: "chocolate",
    origins: ["葉門", "衣索比亞"],
    lineage: "葉門原生古老品種，基因多樣性高，與現代義式「摩卡咖啡」同名但不同",
    vendor: { acidity: 6.0, body: 5.5, sweetness: 5.5, floral: 5.5, fruity: 5.5, chocolate: 7.5 },
    user:   { acidity: 6.2, body: 4.8, sweetness: 5.5, floral: 5.0, fruity: 4.5, chocolate: 7.2 },
    vendorNotes: ["黑巧克力香料（specialty: dark chocolate, spice）", "肉桂豆蔻（specialty: cinnamon, cardamom）", "野生莓果葡萄酒感（specialty: wild berries, winey）", "葉門泥土風土感（specialty: earthy, wild）"],
    userNotes:   ["「葉門日曬讓你認識阿拉伯香料香的根源——肉桂豆蔻深色香料加發酵野莓，像在喝古法製成的中東飲料，不是現代咖啡」（r/Coffee）", "「很野性、不像任何現代精品豆」是喝過的人最常說的話，巧克力香氣濃帶泥土香料（specialty community）", "批次品質波動極大，信任的烘豆師選豆比品種本身更重要——「買葉門豆一定要問清楚來源」（r/Coffee）", "全球最古老商業品種之一，但能喝到真正好批次的機會越來越少，葉門政局讓出口量持續萎縮（r/espresso）"],
  },
  {
    id: "ethiopian-heirloom",
    name: "衣索比亞原生種",
    nameEn: "Ethiopian Heirloom",
    category: "floral",
    origins: ["衣索比亞（耶加雪菲、西達摩、哈拉爾）"],
    lineage: "衣索比亞地方原生品種總稱（估計6,000–15,000個獨特基因型），非單一品種，基因多樣性全球最高",
    vendor: { acidity: 8.0, body: 4.0, sweetness: 8.0, floral: 8.5, fruity: 8.0, chocolate: 1.5 },
    user:   { acidity: 7.5, body: 4.0, sweetness: 7.2, floral: 8.0, fruity: 8.0, chocolate: 1.8 },
    vendorNotes: ["茉莉花（specialty: jasmine）", "藍莓（specialty: blueberry）", "佛手柑（specialty: bergamot）", "桃子熱帶水果（specialty: peach, tropical fruit）"],
    userNotes:   ["水洗耶加雪菲：明亮花香加檸檬，乾淨到透明；日曬西達摩：藍莓葡萄酒感，是截然不同的兩個世界（r/Coffee）", "好的批次在杯子裡就像泡茶，花香不是撲鼻而是若隱若現，讓人一口接一口（r/Coffee）", "Sidama / Guji 近年爬升很快，論壇說「比耶加更有結構，不只是花香表演」（r/espresso）", "「同樣標Ethiopian Heirloom，差距可以天大地大」——要看產區、莊園和處理法，品種名只是起點（r/Coffee）"],
  },
  {
    id: "sudan-rume",
    name: "蘇丹盧美",
    nameEn: "Sudan Rume",
    category: "floral",
    origins: ["蘇丹（Boma Plateau）", "衣索比亞"],
    lineage: "阿拉比卡原始族群之一，源自蘇丹Boma高原，1940年代引入咖啡育種計畫，為Ruiru 11等多個品種的親本",
    vendor: { acidity: 8.5, body: 4.0, sweetness: 7.5, floral: 9.0, fruity: 7.5, chocolate: 2.0 },
    user:   { acidity: 8.0, body: 4.0, sweetness: 7.0, floral: 8.0, fruity: 7.0, chocolate: 2.5 },
    vendorNotes: ["玫瑰馬鞭草（specialty: rose, verbena）", "香茅檸檬草（specialty: lemongrass）", "茶感尾韻（specialty: black tea finish）", "茉莉佛手柑（specialty: jasmine, bergamot）"],
    userNotes:   ["「芒果鳳梨熱帶果香衝出來，酸感精準不刺」（CoffeeReview 品鑑描述）", "有用戶描述喝到的是「紫羅蘭薰衣草帶肉桂」，另一批次又是「茉莉尤加利橙皮」——批次差異驚人", "極度稀有，能找到的批次本身就不多，Home-Barista 論壇常有人問去哪買", "「比藝妓更原始、更野性的花香，但沒那麼精緻」是多數喝過的人的共識"],
  },
  {
    id: "wush-wush",
    name: "諸奇",
    nameEn: "Wush Wush",
    category: "floral",
    origins: ["衣索比亞（卡法地區）"],
    lineage: "衣索比亞卡法森林原生種，近年在哥倫比亞等精品產區廣泛引種種植",
    vendor: { acidity: 8.5, body: 4.0, sweetness: 8.0, floral: 9.0, fruity: 8.0, chocolate: 1.5 },
    user:   { acidity: 8.0, body: 3.8, sweetness: 7.0, floral: 8.5, fruity: 7.5, chocolate: 1.8 },
    vendorNotes: ["茉莉薰衣草（specialty: jasmine, lavender）", "草莓百香果（specialty: strawberry, passion fruit）", "玫瑰水甜感（specialty: rose water sweetness）", "芭樂芒果（specialty: guava, mango）"],
    userNotes:   ["CoffeeReview評95分：芭樂茉莉血橙皮生蜂蜜，「果汁飽滿花香深邃」，尾韻芭樂甜延續好幾分鐘（CoffeeReview）", "日曬版近乎甜點——「powerfully fruity and floral，甜到超標」，有人說喝完不需要再吃甜食（r/Coffee）", "PDG訪問的烘豆師直接說「Unlike anything I had ever tasted before」，是業界引用最多的第一印象（PDG）", "比藝妓稀少，圈內說它「更野性、更原始、更不修邊幅」，但找到好批次的機率比藝妓低很多（r/espresso）"],
  },
  {
    id: "villa-sarchi",
    name: "薇拉薩奇",
    nameEn: "Villa Sarchi",
    category: "balanced",
    origins: ["哥斯大黎加"],
    lineage: "Bourbon-Typica group (Bourbon related)。波旁自然矮化突變種，1950-1960年代哥斯大黎加阿拉胡埃拉省發現，是Sarchimor的親本之一",
    vendor: { acidity: 7.5, body: 5.0, sweetness: 6.5, floral: 4.5, fruity: 7.5, chocolate: 3.5 },
    user:   { acidity: 7.5, body: 4.3, sweetness: 5.5, floral: 4.5, fruity: 6.5, chocolate: 4.0 },
    vendorNotes: ["覆盆子（specialty: raspberry）", "鳳梨汁感（specialty: pineapple）", "精緻果酸（WCR: refined acidity）", "優異甜感（WCR: excellent sweetness）"],
    userNotes:   ["哥斯大黎加塔拉珠蜜處理版被PDG稱為「中美洲精品蜜處理的完美範本」，甜感果酸平衡感極佳（PDG）", "「覆盆子加鳳梨的果酸明亮不失衡，body雖薄但甜感充足，整體比卡杜拉有個性多了」（r/Coffee）", "是薩奇摩的親本，育種貢獻比知名度大很多——「喝Villa Sarchi才知道為什麼薩奇摩有果香基因」（specialty community）", "精品圈中常與卡杜拉做對比，多數人結論是「Villa Sarchi酸感更精緻、甜感更持久」（Home-Barista）"],
  },
  {
    id: "laurina",
    name: "月光/羅利那",
    nameEn: "Laurina (Bourbon Pointu)",
    category: "sweet",
    origins: ["留尼旺島", "中美洲"],
    lineage: "波旁自然突變種，留尼旺島原產，咖啡因含量約0.8%（一般阿拉比卡的一半）",
    vendor: { acidity: 5.0, body: 4.0, sweetness: 8.5, floral: 6.5, fruity: 5.5, chocolate: 2.0 },
    user:   { acidity: 5.8, body: 4.0, sweetness: 7.5, floral: 6.0, fruity: 5.0, chocolate: 2.0 },
    vendorNotes: ["茉莉花茶（specialty: jasmine tea）", "白桃柑橘甜（specialty: white peach, citrus）", "幾乎無苦澀（PDG: barely bitter, very sweet）", "低咖啡因柔和感（specialty: low caffeine, 0.8%）"],
    userNotes:   ["2018年世界手沖賽冠軍Emi Fukahori以Laurina奪冠後，論壇炸鍋：「原來低咖啡因品種可以拿世界冠軍」（r/Coffee）", "「咖啡因只有一般阿拉比卡一半，但甜感花香完全不輸——下午喝了晚上還睡得著，從此愛上它」（r/Coffee）", "甜感偏白桃柑橘，有用戶說「非常純淨，少了一般咖啡的霸道，像在喝精緻花草茶」（Home-Barista）", "栽種困難、產量低，好批次稀有——「找到的話別猶豫，這是敏感族和控制咖啡因攝取者的最佳選擇」（specialty community）"],
  },
  {
    id: "java",
    name: "爪哇",
    nameEn: "Java (Abyssinia)",
    category: "chocolate",
    origins: ["印尼爪哇島", "東非"],
    lineage: "衣索比亞原生種（Abyssinia選系）。WCR確認：源自衣索比亞，非單純印尼鐵比卡系。荷蘭人直接從衣索比亞引入爪哇島",
    vendor: { acidity: 5.5, body: 6.5, sweetness: 5.5, floral: 3.5, fruity: 4.5, chocolate: 7.0 },
    user:   { acidity: 5.2, body: 6.2, sweetness: 5.0, floral: 3.0, fruity: 4.0, chocolate: 7.0 },
    vendorNotes: ["黑巧克力（specialty: dark chocolate）", "菸草丁香香料（specialty: tobacco, clove, spice）", "木質感（specialty: woody）", "乾淨香料尾韻（specialty: clean spice finish）"],
    userNotes:   ["印尼精品圈的發現：「水洗處理後完全不像傳統濕刨法印尼豆，乾淨、有香料層次、很精緻」（r/Coffee）", "「黑巧克力配丁香肉桂，比鐵比卡多了一層辛香，深焙後這個特徵更明顯——很有辨識度」（specialty community）", "Sweet Maria's 記錄其衣索比亞血統，有人說「這才是爪哇咖啡的真正身世，不只是鐵比卡後代」（Sweet Maria's）", "淺焙木質感偏澀，需要中焙才能拉出香料甜感——「是懂得烘焙的人才會愛上的品種」（r/espresso）"],
  },
  {
    id: "castillo",
    name: "卡斯提優",
    nameEn: "Castillo",
    category: "balanced",
    origins: ["哥倫比亞"],
    lineage: "哥倫比亞品種 × 帝汶混血雜交，CENICAFÉ 2005年培育，抗銹病，Caturra × Timor Hybrid",
    vendor: { acidity: 6.5, body: 6.0, sweetness: 6.5, floral: 4.0, fruity: 5.5, chocolate: 5.5 },
    user:   { acidity: 6.0, body: 5.8, sweetness: 5.8, floral: 3.5, fruity: 5.0, chocolate: 5.8 },
    vendorNotes: ["焦糖蘋果（specialty: caramel, apple）", "杏仁堅果（specialty: almond, nuts）", "均衡果酸（specialty: balanced acidity）", "柑橘明亮感（specialty: citrus brightness）"],
    userNotes:   ["PDG 研究：天主教濟世服務盲測顯示Castillo和Caturra杯測分數無顯著差異——「抗病品種也能做出精品」（PDG）", "哥倫比亞主力品種，佔全國產量超過半數——「量大不代表差，好莊園種Castillo照樣拿Cup of Excellence」（r/Coffee）", "「精品圈長期對Castillo有偏見，但高海拔細心處理的批次一出來，很多人改觀了」是近年最常見評語（specialty community）", "Sweet Maria's 評語：均衡乾淨，「哥倫比亞的正確代表——可靠、穩定、不出錯」（Sweet Maria's）"],
  },
  {
    id: "kent",
    name: "肯特",
    nameEn: "Kent",
    category: "chocolate",
    origins: ["印度"],
    lineage: "鐵比卡系選育，1920年代印度Mysore地區Doddengooda Estate選出，是S795的親本之一",
    vendor: { acidity: 5.5, body: 6.0, sweetness: 5.5, floral: 3.0, fruity: 4.0, chocolate: 7.0 },
    user:   { acidity: 5.2, body: 5.8, sweetness: 5.0, floral: 2.8, fruity: 3.5, chocolate: 7.0 },
    vendorNotes: ["低酸甜感（specialty: low acid, mild sweet）", "核桃黑巧克力（specialty: walnut, dark chocolate）", "香料尾韻（specialty: spice finish）", "熱帶果酸（specialty: tropical acidity）"],
    userNotes:   ["印度精品圈評語：「肯特跟S795是印度精品兩大支柱，低酸甜潤特徵是傳統南印咖啡的味覺基礎」（specialty community）", "加牛奶效果極好，「印度南部傳統過濾咖啡（filter coffee）的靈魂就是這個——和牛奶天作之合」（r/Coffee）", "「比想像中乾淨，跟蘇門答臘泥土感截然不同，香料感細緻不粗獷」——第一次喝到優質肯特的常見驚喜（r/Coffee）", "作為S795的親本，研究者說「沒有肯特就沒有印度精品豆的現代化」——育種意義遠超過本身知名度（specialty community）"],
  },
  {
    id: "icatu",
    name: "伊卡圖",
    nameEn: "Icatu",
    category: "chocolate",
    origins: ["巴西"],
    lineage: "羅布斯塔 × 波旁再回交阿拉比卡（Mundo Novo），IAC巴西1985年培育，耐銹病。羅豆血統已通過多代回交稀釋",
    vendor: { acidity: 5.0, body: 7.5, sweetness: 6.0, floral: 2.5, fruity: 4.5, chocolate: 7.5 },
    user:   { acidity: 5.5, body: 6.8, sweetness: 5.5, floral: 2.5, fruity: 4.5, chocolate: 7.0 },
    vendorNotes: ["楓糖麥芽（specialty: maple, malt）", "可可圓潤（specialty: cocoa, round body）", "低調酸質（specialty: subtle acidity）", "焦糖甜感（specialty: caramel sweetness）"],
    userNotes:   ["義式配方烘豆師評語：「卡布奇諾加Icatu，蒸奶後楓糖焦糖感自然放大，不需要任何調味就很甜」（r/espresso）", "「羅布斯塔血統給了它厚重body，但多代回交後土腥感幾乎消失——現代育種的成功案例」（specialty community）", "「做義式不在乎花果香的人，這支就是終點——穩定、厚實、甜，而且比SL系豆子便宜很多」（r/Coffee）", "Sweet Maria's 說它是「巴西人對精品義式的回答」，可可感紮實，適合喜歡厚重感的人（Sweet Maria's）"],
  },
  {
    id: "s795",
    name: "S795",
    nameEn: "S795",
    category: "balanced",
    origins: ["印度", "印尼"],
    lineage: "Kent × S288（S288為帝汶/阿拉比卡混血），CCRI印度選育，1940年代發布，兼顧品質與耐銹病",
    vendor: { acidity: 5.5, body: 6.5, sweetness: 6.5, floral: 4.0, fruity: 4.5, chocolate: 6.0 },
    user:   { acidity: 5.5, body: 6.0, sweetness: 6.0, floral: 3.5, fruity: 4.0, chocolate: 6.5 },
    vendorNotes: ["楓糖漿（specialty: maple syrup）", "焦糖紅糖（specialty: caramel, brown sugar）", "香料感（specialty: spice）", "均衡紮實（specialty: balanced, full body）"],
    userNotes:   ["「印度和印尼精品莊園兩邊都在用，楓糖焦糖感不花俏，但有存在感——是亞洲精品豆裡最值得信任的品種」（specialty community）", "曼特寧和塔那托拉批次常見S795，被說是「十年喝下來從不讓人失望」（r/Coffee）", "「不喜歡酸感的人喝S795通常會喜歡——低調甜、中等body、沒什麼花果香，但整體很舒服」（r/Coffee）", "作為Kent和S288的雜交後代，兼顧品質與耐銹病，是「老一輩專業烘豆師的隱藏最愛」（specialty community）"],
  },
  {
    id: "pink-bourbon",
    name: "粉波旁",
    nameEn: "Pink Bourbon",
    category: "floral",
    origins: ["哥倫比亞（惠拉省）"],
    lineage: "紅波旁與黃波旁自然混種，或含衣索比亞原生基因，2010年前後在哥倫比亞惠拉省出現，確切血統仍有基因研究爭議",
    vendor: { acidity: 8.0, body: 5.0, sweetness: 8.0, floral: 9.0, fruity: 8.5, chocolate: 2.0 },
    user:   { acidity: 7.8, body: 4.8, sweetness: 7.2, floral: 8.5, fruity: 8.0, chocolate: 2.2 },
    vendorNotes: ["玫瑰蜂蜜花香（specialty: rose, honeysuckle）", "荔枝黃桃（specialty: lychee, peach）", "茉莉龍眼蜜（specialty: jasmine, longan honey）", "絲滑甜潤（specialty: silky, sweet）"],
    userNotes:   ["2023世界咖啡師冠軍Boram Um用自家農場的粉波旁奪冠，論壇直接炸鍋：「原來粉波旁可以這麼強」（r/Coffee）", "玫瑰木槿花配芒果百香果荔枝，有人說這是「會讓人忘記在喝咖啡的咖啡」（r/espresso）", "水洗版：茉莉蜜桃，結構清晰；日曬版：玫瑰荔枝龍眼，濃郁到論壇說「喝完忘不掉」（r/Coffee）", "近年價格飛漲，有人說炒作成分多，但真正喝過好批次的都說「有這個價值」（r/Coffee）"],
  },
  {
    id: "yellow-bourbon",
    name: "黃波旁",
    nameEn: "Yellow Bourbon",
    category: "sweet",
    origins: ["巴西", "薩爾瓦多"],
    lineage: "波旁突變種（果實成熟呈黃色），1930年代巴西發現，高果糖含量為甜感來源",
    vendor: { acidity: 6.0, body: 6.5, sweetness: 8.5, floral: 4.5, fruity: 6.5, chocolate: 5.0 },
    user:   { acidity: 5.8, body: 6.0, sweetness: 7.5, floral: 4.0, fruity: 5.5, chocolate: 6.0 },
    vendorNotes: ["蜂蜜杏桃（specialty: honey, apricot）", "香蕉熱帶果香（specialty: banana, tropical）", "極高甜感（specialty: very high sweetness, fructose）", "柑橘酸質平衡（specialty: balanced citric acidity）"],
    userNotes:   ["CoffeeReview 評比Paradise Roasters批次：「成熟桃子、杏桃蜜，酸質柔和如花茶，尾韻甜美持久」（CoffeeReview）", "「黃色果皮比紅波旁更高果糖，手沖慢慢泡出來，甜度高到有人懷疑是不是加了糖」（r/Coffee）", "日曬黃波旁是論壇公認的「甜感轟炸型」，杏桃香蕉熱帶果疊加，有人形容「像在喝果汁不是咖啡」（r/espresso）", "Daily Coffee News 記錄它的復興歷程：消失多年後2019年重新引起精品圈關注，「遲來的正義」（specialty community）"],
  },
  {
    id: "sidra",
    name: "西德拉",
    nameEn: "Sidra",
    category: "fruity",
    origins: ["厄瓜多", "哥倫比亞"],
    lineage: "確切血統有爭議，可能為鐵比卡 × 衣索比亞原生種，或波旁系衍生；厄瓜多與哥倫比亞均有種植",
    vendor: { acidity: 8.5, body: 5.0, sweetness: 8.5, floral: 8.5, fruity: 9.0, chocolate: 1.5 },
    user:   { acidity: 8.2, body: 4.8, sweetness: 7.8, floral: 8.8, fruity: 8.5, chocolate: 1.8 },
    vendorNotes: ["百香果茉莉（specialty: passion fruit, jasmine）", "覆盆子熱帶花香（CoffeeReview: raspberry, tropical floral）", "龍眼蜜甜感（specialty: longan honey sweetness）", "振奮酸質（CoffeeReview avg 93: thrilling acidity）"],
    userNotes:   ["CoffeeReview新品種盲測壓過藝妓和粉波旁奪第一，圈內人直呼「下一個藝妓」（CoffeeReview）", "夏日草莓、西瓜、哈密瓜疊在一起，最後是百香果的爆炸收尾——有人說根本是在喝熱帶果汁（r/espresso）", "哥倫比亞La Palma農場自然發酵批次：強烈果香糖果甜，尾韻延續好幾分鐘，是近年最被討論的批次（r/Coffee）", "2019世界咖啡師大賽冠軍用這支拿冠後，價格直接飛天，論壇說「早買早享受，現在好批次搶不到」（r/Coffee）"],
  },
  {
    id: "maracaturra",
    name: "瑪拉卡杜拉",
    nameEn: "Maracaturra",
    category: "balanced",
    origins: ["尼加拉瓜", "瓜地馬拉"],
    lineage: "象豆（Maragogipe） × 卡杜拉，尼加拉瓜最常見，兼具大豆粒與高酸特性",
    vendor: { acidity: 7.5, body: 5.5, sweetness: 6.5, floral: 6.0, fruity: 7.5, chocolate: 3.0 },
    user:   { acidity: 7.2, body: 5.0, sweetness: 6.0, floral: 6.0, fruity: 7.0, chocolate: 3.5 },
    vendorNotes: ["熱帶水果蜂蜜（specialty: tropical fruit, honey）", "柑橘茉莉花香（specialty: citrus, jasmine）", "清爽明亮酸質（specialty: bright, refined acidity）", "大豆粒均衡感（specialty: large bean, balanced）"],
    userNotes:   ["CoffeeReview 評比尼加拉瓜天然日曬Maracaturra：「鳳梨甜可可薄荷花香，是杯測中讓人驚豔的組合」（CoffeeReview）", "「比象豆乾淨多了，比卡杜拉有個性——大豆粒讓酸感更有結構，喝起來飽滿不尖銳」（r/Coffee）", "在Cup of Excellence 2015得第五名，尼加拉瓜版本被說是「中美洲最被低估的品種之一」（specialty community）", "大豆粒需要調整磨豆設定，「第一次萃取一定做不好，但找到參數後每杯都很穩定」（Home-Barista）"],
  },
  {
    id: "catimor",
    name: "卡帝摩",
    nameEn: "Catimor",
    category: "balanced",
    origins: ["葡萄牙（育種）", "中南美洲", "亞洲廣泛"],
    lineage: "帝汶混血 × 卡杜拉，1959年葡萄牙培育，極抗銹病，羅布斯塔血統佔約25%",
    vendor: { acidity: 6.0, body: 7.0, sweetness: 5.5, floral: 2.5, fruity: 4.5, chocolate: 6.5 },
    user:   { acidity: 6.5, body: 7.0, sweetness: 4.5, floral: 2.0, fruity: 4.0, chocolate: 6.0 },
    vendorNotes: ["黑巧克力堅果（specialty: dark chocolate, nuts）", "草本香氣（specialty: herbal complexity）", "厚重醇感（specialty: medium to full body）", "低花香低果香（specialty: low floral, low fruity）"],
    userNotes:   ["有明顯的土腥感和羅豆基調，淺焙試過的人幾乎都說「不行」", "深焙後巧克力堅果感出來，但很難說是精品咖啡的體驗", "在東南亞和中美洲大量種植，便宜豆包常見身影", "為了抗銹病犧牲了風味，是業界爭議最大的品種之一"],
  },
  {
    id: "sarchimor",
    name: "薩奇摩",
    nameEn: "Sarchimor",
    category: "balanced",
    origins: ["哥斯大黎加", "巴西", "印度"],
    lineage: "帝汶混血 × 薇拉薩奇，1985年哥斯大黎加CATIE培育，耐銹病",
    vendor: { acidity: 6.5, body: 5.5, sweetness: 6.5, floral: 4.5, fruity: 6.0, chocolate: 4.5 },
    user:   { acidity: 6.8, body: 5.3, sweetness: 5.8, floral: 4.0, fruity: 5.5, chocolate: 5.0 },
    vendorNotes: ["桃子蜂蜜（specialty: peach, honey）", "輕盈花香（specialty: light floral）", "乾淨酸質（specialty: clean acidity）", "均衡甜感（specialty: balanced sweetness）"],
    userNotes:   ["「比卡帝摩乾淨很多很多——同樣有帝汶混血基因，但薇拉薩奇的果酸基因稀釋了土腥感」（r/Coffee）", "哥斯大黎加蜜處理薩奇摩被PDG譽為「中美洲蜜處理最值得探索的品種之一」，桃子蜂蜜感明顯（PDG）", "印度版本（如Double Diamond等選系）有時表現讓人驚喜，「超過當地S795」（specialty community）", "Sucafina 杯測報告記錄柳橙蘋果梨子酸質——「是可以認真做精品的抗病品種，不只是農業妥協品」（specialty community）"],
  },
  {
    id: "ruiru11",
    name: "盧伊魯11",
    nameEn: "Ruiru 11",
    category: "balanced",
    origins: ["肯亞"],
    lineage: "多重雜交品種：母本為Catimor（Caturra × Timor Hybrid），父本為K7、SL28、N39、Rume Sudan多元混血，1985年肯亞研究站培育",
    vendor: { acidity: 7.5, body: 7.5, sweetness: 6.0, floral: 4.0, fruity: 6.5, chocolate: 5.5 },
    user:   { acidity: 7.8, body: 7.0, sweetness: 5.2, floral: 3.5, fruity: 6.0, chocolate: 5.8 },
    vendorNotes: ["黑醋栗深色莓果（specialty: blackcurrant, dark berries）", "強烈酸質（specialty: intense acidity）", "厚實醇感（WCR: high body）", "複雜抗病品系（WCR: K7+SL28+Rume Sudan hybrid）"],
    userNotes:   ["「有些人說近年肯亞豆的『黑醋栗炸彈』變少了，就是因為SL品種被Ruiru 11取代——圈內一直在爭這件事」（r/Coffee）", "高海拔批次可以出現醋栗茶感、黑莓葡萄柚複雜度——「低海拔確實不行，但別一竿子打翻一船人」（specialty community）", "Mission Coffee Works 記錄：Ruiru 11含有SL28、Sudan Rume血統，頂批潛力被大多數人低估（specialty community）", "「比SL28便宜、比卡帝摩好喝，但永遠在SL的光環下，論壇很少人專門討論Ruiru 11本身」（r/Coffee）"],
  },
  {
    id: "batian",
    name: "巴提安",
    nameEn: "Batian",
    category: "balanced",
    origins: ["肯亞"],
    lineage: "多重雜交（含SL28、SL34、Rume Sudan、N39、K7、SL4及Timor Hybrid血統），2010年肯亞KALRO最新選育",
    vendor: { acidity: 8.0, body: 6.5, sweetness: 6.5, floral: 5.0, fruity: 7.5, chocolate: 4.5 },
    user:   { acidity: 7.8, body: 6.2, sweetness: 6.0, floral: 4.5, fruity: 7.0, chocolate: 5.0 },
    vendorNotes: ["黑莓柚子（specialty: blackberry, pomelo）", "磷酸感（specialty: phosphoric）", "複雜果酸（specialty: complex fruit acidity）", "紮實醇感（WCR: very good quality）"],
    userNotes:   ["PDG 2016年報導：「Batian是肯亞的賭注——能抗病又能在競賽桌上打敗SL28嗎？答案開始越來越像是肯定的」（PDG）", "高海拔1700m以上批次：成熟梅子、柚子皮、茉莉花香——「不輸SL28，高品質批次喝過的人幾乎都翻供了」（specialty community）", "Mission Coffee Works杯測：酸感精緻複雜，果香結構清楚，比Ruiru 11更接近SL品種的表現（specialty community）", "「幾乎不可能單獨找到，通常混在SL28和SL34批次裡——這是Batian最大的委屈」（r/Coffee）"],
  },
  {
    id: "blue-mountain",
    name: "藍山",
    nameEn: "Blue Mountain",
    category: "balanced",
    origins: ["牙買加", "巴布亞新幾內亞", "肯亞"],
    lineage: "鐵比卡系選育，18世紀英國引入牙買加藍山地區，現為地理保護品種；別名為Typica在牙買加的稱呼",
    vendor: { acidity: 5.0, body: 6.5, sweetness: 7.5, floral: 5.0, fruity: 5.0, chocolate: 5.5 },
    user:   { acidity: 5.2, body: 6.0, sweetness: 6.2, floral: 4.2, fruity: 4.5, chocolate: 5.8 },
    vendorNotes: ["奶油感（specialty: buttery, creamy）", "茉莉花香（specialty: jasmine floral）", "焦糖蜂蜜甜感（specialty: caramel, honey）", "無瑕疵乾淨（specialty: clean, flaw-free）"],
    userNotes:   ["「名氣和定價遠超過實際風味體驗」是r/Coffee最常見的評語", "乾淨優雅是真的，但論壇普遍覺得「為這個付那個價格不值得」", "適合喜歡低調、不愛強烈酸感的人，是長輩最常誇的咖啡之一", "Papua New Guinea 藍山系統批次評價比牙買加本身還要高，但品牌效應還是在牙買加"],
  },
  {
    id: "tabi",
    name: "塔比",
    nameEn: "Tabi",
    category: "balanced",
    origins: ["哥倫比亞"],
    lineage: "鐵比卡 × 帝汶混血 × 波旁三系雜交，2002年哥倫比亞CENICAFÉ培育，名稱源自Guambiano原住民語「good」",
    vendor: { acidity: 7.0, body: 5.5, sweetness: 7.5, floral: 7.0, fruity: 7.0, chocolate: 3.5 },
    user:   { acidity: 7.2, body: 5.2, sweetness: 7.0, floral: 7.0, fruity: 6.5, chocolate: 3.5 },
    vendorNotes: ["茉莉花香（specialty: jasmine）", "柑橘蘋果酸質（specialty: citric, sweet apple）", "橙子紅莓（specialty: orange, red berries）", "細緻蜂蜜感（specialty: honey, delicate）"],
    userNotes:   ["「哥倫比亞隱藏版寶藏：花香比Castillo明顯，甜感比Caturra好，喝到的人幾乎都說『早點認識就好了』」（r/Coffee）", "CENICAFÉ育種25年才發布，茉莉柑橘蘋果交疊，有人說是「哥倫比亞版花果型均衡代表」（specialty community）", "「Tabi在瓜地馬拉語是『好』，喝過的烘豆師說這個名字取得實在太精準了」（specialty community）", "近年在哥倫比亞競賽批次頻繁出現，Sey Coffee等精品烘焙商開始積極收購——「關注度正在快速上升」（specialty community）"],
  },
  {
    id: "obata",
    name: "歐巴塔",
    nameEn: "Obatã",
    category: "balanced",
    origins: ["巴西"],
    lineage: "Timor Hybrid 832/2 × Villa Sarchi CIFC 971/10，IAC巴西農研所選育，2000年巴西發布，2014年哥斯大黎加引種。WCR確認無黃波旁血統",
    vendor: { acidity: 6.5, body: 6.5, sweetness: 6.5, floral: 4.0, fruity: 5.5, chocolate: 6.0 },
    user:   { acidity: 6.2, body: 6.2, sweetness: 6.0, floral: 3.5, fruity: 5.0, chocolate: 6.5 },
    vendorNotes: ["焦糖牛奶巧克力（specialty: caramel, milk chocolate）", "輕微果酸（specialty: light fruit acidity）", "均衡厚實（specialty: balanced, full）", "高產穩定（WCR: high yield, rust-resistant）"],
    userNotes:   ["Cup of Excellence Mexico 2024 第七名：一支Obata獲得87.58分，「讓很多人開始重新評估這個品種的上限」（specialty community）", "April Coffee 發現Obata可以呈現非常細緻的焦糖棕糖感，「比一般巴西品種更有層次」（PDG）", "「耐銹病、高產量、好萃取——生豆貿易圈說它是下一個會紅的品種，現在入手正是時候」（r/Coffee）", "巴西和哥斯大黎加積極推廣，Hacienda Sonora的批次已進入精品市場，口碑在圈內快速建立（specialty community）"],
  },
  {
    id: "timor-hybrid",
    name: "帝汶混血",
    nameEn: "Timor Hybrid (HDT)",
    category: "chocolate",
    origins: ["東帝汶", "印尼"],
    lineage: "阿拉比卡與羅布斯塔1920年代東帝汶自然雜交，1927年發現，是眾多抗病品種（Catimor、Sarchimor、Castillo）的關鍵親本",
    vendor: { acidity: 4.5, body: 8.5, sweetness: 5.0, floral: 2.0, fruity: 3.5, chocolate: 7.0 },
    user:   { acidity: 5.5, body: 7.5, sweetness: 4.0, floral: 1.8, fruity: 3.0, chocolate: 7.5 },
    vendorNotes: ["深色巧克力（specialty: dark chocolate）", "泥土礦物感（specialty: earthy, mineral）", "厚重醇感（specialty: bold body）", "低調微酸（specialty: subtle acidity）"],
    userNotes:   ["Sweet Maria's 評語：「HDT的意義在於它是幾乎所有現代抗病品種的遺傳基礎——沒有它就沒有Catimor、Sarchimor和Castillo」（Sweet Maria's）", "「直接喝帝汶混血原生批次的人說：Giling Basah處理法的影響比品種本身更強，但換水洗後意外出現杏桃石果感」（r/Coffee）", "「育種貢獻大於杯測魅力的品種——花果香系的人看到它通常直接跳過，厚重body和低調巧克力是真實存在的」（specialty community）", "東帝汶當地版本日曬後有報告記錄到「出乎意料的熱帶水果感，說明其阿拉比卡基因沒有被完全掩蓋」（specialty community）"],
  },
  {
    id: "marsellesa",
    name: "馬賽雷薩",
    nameEn: "Marsellesa",
    category: "balanced",
    origins: ["中美洲（尼加拉瓜、宏都拉斯）"],
    lineage: "Timor Hybrid 832/2 × Villa Sarchi CIFC 971/10，CIRAD-ECOM研發，2009年尼加拉瓜發布，薩奇摩相關品系",
    vendor: { acidity: 7.5, body: 6.0, sweetness: 6.5, floral: 6.0, fruity: 6.5, chocolate: 4.5 },
    user:   { acidity: 6.8, body: 5.8, sweetness: 6.0, floral: 5.5, fruity: 6.0, chocolate: 5.0 },
    vendorNotes: ["桃子果香（WCR: fruity, floral fragrance）", "比卡杜拉更甜（specialty: sweeter than Caturra）", "高酸質（WCR: notably high acidity）", "乾淨焦糖感（specialty: clean, caramel）"],
    userNotes:   ["Ratiocraft 記錄：「Marsellesa是中美洲最被低估的現代品種之一，均衡甜潤乾淨，比多數人想像中好很多」（specialty community）", "「比卡帝摩高幾個檔次——蜜橙花香配焦糖奶油，令人驚喜地展現出Villa Sarchi的果香基因」（r/Coffee）", "尼加拉瓜和瓜地馬拉精品莊園在用，WCR評其為酸質明顯、甜感佳的抗病優秀品種——「是農業妥協，也是好咖啡」（specialty community）", "Sweet Maria's 說它在中美洲高海拔條件下可以展現細緻花果甜感，「對抗病品種有成見的人需要重新嘗試這支」（Sweet Maria's）"],
  },
  {
    id: "harrar",
    name: "哈拉爾",
    nameEn: "Harrar",
    category: "fruity",
    origins: ["衣索比亞（哈拉爾地區）"],
    lineage: "衣索比亞東部高地原生品種群，幾乎全為傳統日曬處理，基因多樣性高",
    vendor: { acidity: 7.5, body: 6.5, sweetness: 7.0, floral: 6.0, fruity: 8.5, chocolate: 3.5 },
    user:   { acidity: 7.2, body: 5.0, sweetness: 6.5, floral: 5.5, fruity: 8.0, chocolate: 3.5 },
    vendorNotes: ["藍莓黑莓（specialty: blueberry jam, blackberry）", "葡萄酒發酵感（specialty: winey）", "杏桃深色香料（specialty: dried apricot, cinnamon）", "濃郁厚重（specialty: full, syrupy body）"],
    userNotes:   ["Sweet Maria's記錄：有人說第一次喝到哈拉爾就像喝到藍莓汁，從此因此愛上咖啡——這種故事在論壇很常見（specialty community）", "野性大膽果醬感：藍莓派配黑巧克力，厚重葡萄酒質感，有人說這是「最有個性的非洲豆，沒有之一」（r/Coffee）", "愛它和討厭它的人一樣多：「野莓發酵感讓我著迷」vs「像爛水果，真的喝不下去」——兩邊都是真心話（r/Coffee）", "真正的老哈拉爾批次據說是傳說，近年工業化後品質不穩——要認識信任的烘豆師才能買到好東西（r/espresso）"],
  },
];

export const CATEGORY_LABELS: Record<FlavorCategory, string> = {
  floral:     "花香型",
  fruity:     "果香型",
  sweet:      "甜感型",
  chocolate:  "巧克力型",
  balanced:   "均衡型",
  bold:       "強勁型",
};

export const CATEGORY_COLORS: Record<FlavorCategory, string> = {
  floral:    "#e879f9",
  fruity:    "#fb923c",
  sweet:     "#fbbf24",
  chocolate: "#a16207",
  balanced:  "#2dd4bf",
  bold:      "#3b5bdb",
};

export const FLAVOR_DIMS = [
  { key: "acidity",   label: "酸度" },
  { key: "body",      label: "醇厚度" },
  { key: "sweetness", label: "甜感" },
  { key: "floral",    label: "花香" },
  { key: "fruity",    label: "果香" },
  { key: "chocolate", label: "可可/堅果" },
] as const;

export type FlavorDimKey = typeof FLAVOR_DIMS[number]["key"];
